// GENERATED by tools/build-models.js — do not edit by hand.
// Art: Kenney 3D kits, CC0 (https://kenney.nl). Models and their animations
// are Kenney's work, embedded here so the game runs from a local file.
(function (root, factory) {
  var api = factory();
  if (typeof module === "object" && module.exports) module.exports = api;
  else root.MODEL_META = api;
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  return {
    "building-a": {
      "w": 0.884,
      "h": 1.293,
      "d": 0.94,
      "cx": 0,
      "cy": 0,
      "cz": 0
    },
    "building-c": {
      "w": 0.884,
      "h": 0.893,
      "d": 1.09,
      "cx": 0,
      "cy": 0,
      "cz": 0
    },
    "building-e": {
      "w": 1.64,
      "h": 0.893,
      "d": 1.008,
      "cx": 0,
      "cy": 0,
      "cz": 0
    },
    "building-h": {
      "w": 0.884,
      "h": 1.293,
      "d": 1.008,
      "cx": 0,
      "cy": 0,
      "cz": 0
    },
    "building-k": {
      "w": 2.084,
      "h": 1.47,
      "d": 0.942,
      "cx": 0,
      "cy": 0,
      "cz": 0
    },
    "building-n": {
      "w": 2.32,
      "h": 2.48,
      "d": 1.82,
      "cx": 0,
      "cy": 0,
      "cz": 0
    },
    "tower-a": {
      "w": 1.36,
      "h": 2.88,
      "d": 1.36,
      "cx": 0,
      "cy": 0,
      "cz": 0
    },
    "tower-c": {
      "w": 1.28,
      "h": 4.08,
      "d": 1.388,
      "cx": 0,
      "cy": 0,
      "cz": 0
    },
    "bank": {
      "w": 2.084,
      "h": 1.693,
      "d": 1.34,
      "cx": 0,
      "cy": 0,
      "cz": 0
    },
    "road-straight": {
      "w": 1,
      "h": 0.02,
      "d": 1,
      "cx": 0,
      "cy": 0,
      "cz": 0
    },
    "road-crossroad": {
      "w": 1,
      "h": 0.02,
      "d": 1,
      "cx": 0,
      "cy": 0,
      "cz": 0
    },
    "car-sedan": {
      "w": 1.5,
      "h": 1.3,
      "d": 2.55,
      "cx": 0,
      "cy": 0,
      "cz": -0.025
    },
    "car-taxi": {
      "w": 1.5,
      "h": 1.5,
      "d": 2.75,
      "cx": 0,
      "cy": 0,
      "cz": -0.025
    },
    "car-van": {
      "w": 1.5,
      "h": 1.35,
      "d": 2.75,
      "cx": 0,
      "cy": 0,
      "cz": -0.025
    },
    "car-suv": {
      "w": 1.5,
      "h": 1.3,
      "d": 2.7,
      "cx": 0,
      "cy": 0,
      "cz": 0
    },
    "car-sports": {
      "w": 1.3,
      "h": 1.1,
      "d": 2.85,
      "cx": 0,
      "cy": 0,
      "cz": -0.025
    },
    "car-police": {
      "w": 1.5,
      "h": 1.3,
      "d": 3.1,
      "cx": 0,
      "cy": 0,
      "cz": 0
    },
    "cop": {
      "w": 1.6,
      "h": 2.7,
      "d": 0.8,
      "cx": 0,
      "cy": 0,
      "cz": 0,
      "animations": [
        "static",
        "idle",
        "walk",
        "sprint",
        "sit",
        "drive",
        "die",
        "pick-up",
        "emote-yes",
        "emote-no",
        "holding-right",
        "holding-left",
        "holding-both",
        "holding-right-shoot",
        "holding-left-shoot",
        "holding-both-shoot",
        "attack-melee-right",
        "attack-melee-left",
        "attack-kick-right",
        "attack-kick-left",
        "interact-right",
        "interact-left",
        "wheelchair-sit",
        "wheelchair-move-forward",
        "wheelchair-move-back",
        "wheelchair-move-left",
        "wheelchair-move-right"
      ]
    },
    "civ-a": {
      "w": 1.6,
      "h": 2.7,
      "d": 0.8,
      "cx": 0,
      "cy": 0,
      "cz": 0,
      "animations": [
        "static",
        "idle",
        "walk",
        "sprint",
        "sit",
        "drive",
        "die",
        "pick-up",
        "emote-yes",
        "emote-no",
        "holding-right",
        "holding-left",
        "holding-both",
        "holding-right-shoot",
        "holding-left-shoot",
        "holding-both-shoot",
        "attack-melee-right",
        "attack-melee-left",
        "attack-kick-right",
        "attack-kick-left",
        "interact-right",
        "interact-left",
        "wheelchair-sit",
        "wheelchair-move-forward",
        "wheelchair-move-back",
        "wheelchair-move-left",
        "wheelchair-move-right"
      ]
    },
    "civ-b": {
      "w": 1.6,
      "h": 2.7,
      "d": 0.8,
      "cx": 0,
      "cy": 0,
      "cz": 0,
      "animations": [
        "static",
        "idle",
        "walk",
        "sprint",
        "sit",
        "drive",
        "die",
        "pick-up",
        "emote-yes",
        "emote-no",
        "holding-right",
        "holding-left",
        "holding-both",
        "holding-right-shoot",
        "holding-left-shoot",
        "holding-both-shoot",
        "attack-melee-right",
        "attack-melee-left",
        "attack-kick-right",
        "attack-kick-left",
        "interact-right",
        "interact-left",
        "wheelchair-sit",
        "wheelchair-move-forward",
        "wheelchair-move-back",
        "wheelchair-move-left",
        "wheelchair-move-right"
      ]
    },
    "blaster": {
      "w": 0.184,
      "h": 0.456,
      "d": 0.8,
      "cx": 0,
      "cy": -0.303,
      "cz": 0.03
    },
    "atm": {
      "w": 0.43,
      "h": 0.92,
      "d": 0.292,
      "cx": 0.215,
      "cy": 0,
      "cz": -0.136
    },
    "till": {
      "w": 0.734,
      "h": 0.384,
      "d": 0.392,
      "cx": 0.357,
      "cy": 0,
      "cz": -0.184
    },
    "till-screen": {
      "w": 0.393,
      "h": 0.294,
      "d": 0.104,
      "cx": 0.196,
      "cy": 0,
      "cz": -0.052
    },
    "vault": {
      "w": 1,
      "h": 1,
      "d": 1,
      "cx": 0,
      "cy": 0,
      "cz": 0
    },
    "streetlight": {
      "w": 0.05,
      "h": 0.6,
      "d": 0.238,
      "cx": 0,
      "cy": 0,
      "cz": -0.094
    },
    "traffic-light": {
      "w": 0.118,
      "h": 0.515,
      "d": 0.09,
      "cx": -0.014,
      "cy": 0,
      "cz": 0
    },
    "dumpster": {
      "w": 0.275,
      "h": 0.209,
      "d": 0.37,
      "cx": 0.008,
      "cy": 0,
      "cz": 0
    },
    "tree": {
      "w": 1.04,
      "h": 1.46,
      "d": 1.04,
      "cx": 0,
      "cy": 0,
      "cz": 0
    }
  };
});
