// GTA Fun — the simulation. Pure numbers: no Three.js, no DOM, no canvas.
// Everything the game *is* lives here; rendering only reads this state.
// That split is what lets the whole game be playtested headlessly in Node.
(function (root, factory) {
  var api = factory();
  if (typeof module === 'object' && module.exports) module.exports = api;
  else root.SIM = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  'use strict';

  // Native sizes of the Kenney models, generated by tools/build-models.js.
  // The sim needs them so collision boxes match what you actually see.
  var META = (typeof module === 'object' && module.exports)
    ? require('./model-meta.js')
    : (typeof globalThis !== 'undefined' ? globalThis.MODEL_META : null);

  // Every blaster is a different Kenney model with its own feel. Prices are in
  // the same fake money you take off cash machines.
  var WEAPONS = [
    { id: 'blaster', name: 'Standard Blaster', model: 'blaster',
      damage: 14, delay: 0.22, spread: 0.012, mag: 40, pellets: 1, price: 0,
      blurb: 'the one you find lying around' },
    { id: 'rapid', name: 'Rapid Blaster', model: 'blaster-rapid',
      damage: 8, delay: 0.09, spread: 0.05, mag: 90, pellets: 1, price: 400,
      blurb: 'fires very fast, aims very badly' },
    { id: 'scatter', name: 'Scatter Blaster', model: 'blaster-scatter',
      damage: 9, delay: 0.65, spread: 0.14, mag: 28, pellets: 5, price: 750,
      blurb: 'five darts at once, close range' },
    { id: 'heavy', name: 'Heavy Blaster', model: 'blaster-heavy',
      damage: 34, delay: 0.7, spread: 0.006, mag: 22, pellets: 1, price: 1100,
      blurb: 'slow, heavy, sits an officer down in three' },
    { id: 'long', name: 'Long Shot', model: 'blaster-long',
      damage: 60, delay: 1.15, spread: 0, mag: 12, pellets: 1, price: 1600,
      blurb: 'one dart, one very surprised officer' },
  ];

  // Levels hand out permanent perks. Nothing to equip or manage: reach the
  // level and it applies itself.
  var PERKS = [
    { level: 2, id: 'quick', name: 'Quick Fingers', blurb: 'robberies take half as long' },
    { level: 3, id: 'tough', name: 'Thick Skin', blurb: '+40 maximum health' },
    { level: 4, id: 'runner', name: 'Road Runner', blurb: 'you sprint noticeably faster' },
    { level: 5, id: 'scrounger', name: 'Scrounger', blurb: 'chests and tills pay more' },
    { level: 6, id: 'nerves', name: 'Steady Nerves', blurb: 'you take less from a dart' },
    { level: 7, id: 'ghost', name: 'Ghost', blurb: 'the heat cools twice as fast' },
  ];

  function weaponById(id) {
    for (var i = 0; i < WEAPONS.length; i++) if (WEAPONS[i].id === id) return WEAPONS[i];
    return WEAPONS[0];
  }

  // What the armoury sells. Weapons come from the table above.
  function storeStock() {
    var items = [];
    for (var i = 1; i < WEAPONS.length; i++) {
      items.push({ kind: 'weapon', weapon: WEAPONS[i].id, name: WEAPONS[i].name,
        price: WEAPONS[i].price, blurb: WEAPONS[i].blurb });
    }
    items.push({ kind: 'ammo', name: 'Ammo pack', price: 120,
      blurb: 'refills the blaster you are holding' });
    items.push({ kind: 'medkit', name: 'Med kit', price: 200,
      blurb: 'press H to heal ' + C.MEDKIT_HEAL + ' health' });
    return items;
  }

  var BUILDING_MODELS = ['building-a', 'building-c', 'building-e', 'building-h',
    'building-k', 'building-n', 'tower-a', 'tower-c'];
  var CAR_MODELS = ['car-sedan', 'car-taxi', 'car-van', 'car-suv', 'car-sports'];
  // Eight different people, so the street is not one man repeated.
  var CIVILIAN_MODELS = ['civ-a', 'civ-b', 'civ-c', 'civ-d', 'civ-e', 'civ-f', 'civ-g', 'civ-h'];

  // Uniform scale that makes a model's footprint fill a lot of the given size.
  function fitScale(name, target) {
    var m = META && META[name];
    if (!m) return { scale: 1, w: target, d: target, h: target };
    var scale = target / Math.max(m.w, m.d);
    return { scale: scale, w: m.w * scale, d: m.d * scale, h: m.h * scale };
  }

  var C = {
    BLOCKS: 6,
    BLOCK: 60,
    ROAD: 18,
    WALK: 6.2,
    TURN_SPEED: 2.5,          // arrow-key turning, for players who dislike mouselook
    SPRINT: 9.4,
    PLAYER_R: 0.6,
    EYE: 1.7,

    CAR_MAX: 30,
    CAR_ACCEL: 16,
    CAR_BRAKE: 26,
    CAR_DRAG: 0.7,
    CAR_TURN: 1.7,
    CAR_R: 1.3,               // was 1.7: too fat, so cars wedged on kerbs

    MAX_HEALTH: 100,
    REGEN_DELAY: 6,
    REGEN_RATE: 5,

    COP_HEALTH: 100,
    COP_HIT_R: 1.1,
    COP_ARMED_SHARE: 0.7,     // the rest turn up without a blaster
    COP_GRAB_RANGE: 2.2,
    COP_GRAB_DAMAGE: 3,
    COP_GRAB_DELAY: 1.4,
    FOOT_POLICE_CARS: 1,      // cars sent while you are on foot
    FOOT_CAR_STANDOFF: 26,    // and how far back they hold
    WINDOW_HEALTH: 20,
    CHEST_RANGE: 2.8,
    DAY_LENGTH: 300,          // seconds for a full day and night
    XP_PER_LEVEL: 220,
    HIT_FLASH: 0.18,           // officers stand 2.35m; give darts a fair target
    COP_SPEED: 4.6,
    COP_RANGE: 22,
    COP_STANDOFF: 9,
    // Tuned down hard after a playtest: at 7 damage every 1.35s, three officers
    // took a standing player from 100 to 23 in ten seconds. These are children.
    COP_FIRE_DELAY: 2.0,
    COP_DART_SPEED: 34,
    COP_DART_DAMAGE: 4,
    // Half a second of grace after each hit, so a crowd of officers cannot
    // stack their volleys and melt you before you can react.
    HIT_GRACE: 0.5,

    DART_SPEED: 55,
    DART_DAMAGE: 14,
    DART_LIFE: 2.2,
    FIRE_DELAY: 0.22,
    MAG: 40,

    MAX_WANTED: 5,
    WANTED_DECAY: 28,
    ROB_TIME: 2.6,
    ROB_RANGE: 3.4,
    ROB_COOLDOWN: 45,
    ENTER_RANGE: 4.0,
    PICKUP_RANGE: 2.2,
    STORE_RANGE: 3.6,
    DOOR_RANGE: 3.8,
    MEDKIT_HEAL: 50,

    MAX_COPS: 10,
    MAX_POLICE_CARS: 5,
    AUTO_SPRINT_AFTER: 1.1,   // keep running forward and you break into a jog
    DROP_RANGE: 1.8,
    // Was 2.2m within 29 degrees, which meant walking into a door dead-on or
    // nothing happened at all. Wider on both counts.
    AUTO_DOOR_RANGE: 3.6,
    AUTO_DOOR_FACING: 1.15,   // radians off straight-ahead that still counts

    JUMP_SPEED: 6.4,
    GRAVITY: 18,

    MELEE_RANGE: 2.8,
    MELEE_DAMAGE: 26,
    MELEE_DELAY: 0.55,
    MELEE_ARC: 1.1,           // radians either side of straight ahead

    CIVILIANS: 9,
    CIV_SPEED: 3.6,
    CIV_FLEE_SPEED: 6.6,
    CIV_HEALTH: 60,
    CIV_BRAVE: 0.28,          // share who join in rather than run
    CIV_FIRE_DELAY: 1.6,
    CIV_DART_DAMAGE: 6,
    CIV_RANGE: 20,
    CIV_TURN: 4.5,            // radians per second a person can turn

    DOWNED_FORGET: 140,       // how far you must get before a body is tidied away
    HIDEOUT_DECAY: 4,         // the heat drops this much faster while hidden
    BREAK_IN_TIME: 1.6,

    RUN_OVER_SPEED: 6,        // how fast you must be going to flatten an officer
  };

  C.WORLD = C.BLOCKS * C.BLOCK;
  C.HALF_ROAD = C.ROAD / 2;

  function mulberry32(a) {
    return function () {
      a |= 0; a = (a + 0x6D2B79F5) | 0;
      var t = Math.imul(a ^ (a >>> 15), 1 | a);
      t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
      return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    };
  }

  function clamp(v, lo, hi) { return v < lo ? lo : v > hi ? hi : v; }
  function dist2(ax, az, bx, bz) { var dx = ax - bx, dz = az - bz; return dx * dx + dz * dz; }
  function dist(ax, az, bx, bz) { return Math.sqrt(dist2(ax, az, bx, bz)); }

  // Closest distance from a point to a line segment, on the ground plane.
  // Darts are tested along the whole step they travelled, not just where they
  // landed: at 55 m/s a dart advances further per frame than a person is wide,
  // so a position-only test lets them pass straight through an officer — and it
  // gets worse the more the game stutters.
  function segmentDistance(ax, az, bx, bz, cx, cz) {
    var dx = bx - ax, dz = bz - az;
    var len2 = dx * dx + dz * dz;
    var t = len2 > 0 ? ((cx - ax) * dx + (cz - az) * dz) / len2 : 0;
    t = clamp(t, 0, 1);
    return Math.hypot(ax + dx * t - cx, az + dz * t - cz);
  }

  // Yaw 0 looks down -Z, matching the renderer's camera.
  function forwardX(yaw) { return -Math.sin(yaw); }
  function forwardZ(yaw) { return -Math.cos(yaw); }
  // The inverse: the yaw that points along a direction.
  function yawTowards(dx, dz) { return Math.atan2(-dx, -dz); }

  // --- city -----------------------------------------------------------------

  function buildCity(rnd) {
    var boxes = [];          // solid AABBs: buildings and the town wall
    var buildings = [];      // placed Kenney models, with the scale to draw them at
    var loot = [];
    var doors = [];          // ways into interiors, not things you rob
    var windows = [];        // shoot them out for another way in
    var chests = [];         // crates of odds and ends
    var guns = [];
    var props = [];          // pure decoration: lamps, trees, bins
    var blockInfo = [];

    var inner = C.BLOCK - C.ROAD;                 // 42 metres of buildable lot

    function place(name, cx, cz, target, rot) {
      var fit = fitScale(name, target);
      var w = (rot % 2) ? fit.d : fit.w;
      var d = (rot % 2) ? fit.w : fit.d;
      buildings.push({
        model: name, x: cx, z: cz, rot: rot * Math.PI / 2,
        scale: fit.scale, w: w, d: d, h: fit.h
      });
      boxes.push({ x0: cx - w / 2, z0: cz - d / 2, x1: cx + w / 2, z1: cz + d / 2 });
      return { w: w, d: d, h: fit.h };
    }

    for (var j = 0; j < C.BLOCKS; j++) {
      for (var i = 0; i < C.BLOCKS; i++) {
        var x0 = i * C.BLOCK + C.HALF_ROAD;
        var z0 = j * C.BLOCK + C.HALF_ROAD;
        var cx = x0 + inner / 2, cz = z0 + inner / 2;
        var isBank = (i === 2 && j === 3) || (i === 4 && j === 1);
        blockInfo.push({ i: i, j: j, x0: x0, z0: z0, w: inner, bank: isBank });

        if (isBank) {
          var bank = place('bank', cx, cz, inner - 8, 0);
          // The vault door on the street-facing wall is the way in, not loot.
          doors.push({ kind: 'bank', x: cx, z: cz + bank.d / 2 + 1.6, facing: 0 });
          props.push({ model: 'tree', x: cx - bank.w / 2 - 4, z: cz + bank.d / 2 + 2, rot: 0, size: 6 });
          props.push({ model: 'tree', x: cx + bank.w / 2 + 4, z: cz + bank.d / 2 + 2, rot: 0, size: 6 });
          continue;
        }

        // One big building, or four smaller ones with alleys between them.
        if (rnd() < 0.4) {
          place(BUILDING_MODELS[Math.floor(rnd() * BUILDING_MODELS.length)],
            cx, cz, inner - 6, Math.floor(rnd() * 4));
        } else {
          var cell = inner / 2;
          for (var lj = 0; lj < 2; lj++) {
            for (var li = 0; li < 2; li++) {
              if (rnd() < 0.15) {
                // An empty lot: park it out rather than leaving a hole.
                props.push({
                  model: 'tree', rot: 0, size: 5 + rnd() * 3,
                  x: x0 + li * cell + cell / 2, z: z0 + lj * cell + cell / 2
                });
                continue;
              }
              place(BUILDING_MODELS[Math.floor(rnd() * BUILDING_MODELS.length)],
                x0 + li * cell + cell / 2, z0 + lj * cell + cell / 2,
                cell - 4, Math.floor(rnd() * 4));
            }
          }
        }

        // A cash machine against the pavement, always facing a road.
        var side = Math.floor(rnd() * 4);
        var atm = { kind: 'atm', cash: 260, cool: 0 };
        if (side === 0) { atm.x = cx; atm.z = z0 - 1.4; atm.facing = Math.PI; }
        else if (side === 1) { atm.x = cx; atm.z = z0 + inner + 1.4; atm.facing = 0; }
        else if (side === 2) { atm.x = x0 - 1.4; atm.z = cz; atm.facing = Math.PI / 2; }
        else { atm.x = x0 + inner + 1.4; atm.z = cz; atm.facing = -Math.PI / 2; }
        loot.push(atm);

        // Every third block gets a market till on the opposite pavement.
        if ((i + j) % 3 === 0) {
          var s2 = (side + 2) % 4;
          var reg = { kind: 'register', cash: 480, cool: 0 };
          if (s2 === 0) { reg.x = cx + 7; reg.z = z0 - 1.6; reg.facing = Math.PI; }
          else if (s2 === 1) { reg.x = cx - 7; reg.z = z0 + inner + 1.6; reg.facing = 0; }
          else if (s2 === 2) { reg.x = x0 - 1.6; reg.z = cz + 7; reg.facing = Math.PI / 2; }
          else { reg.x = x0 + inner + 1.6; reg.z = cz - 7; reg.facing = -Math.PI / 2; }
          loot.push(reg);
        }

        if (rnd() < 0.4) guns.push({ x: cx + 4 + rnd() * 6, z: z0 - 3, taken: false });
        if ((i * 3 + j) % 2 === 0) {
          // A window on the street: shoot it out and climb in that way.
          windows.push({
            x: cx + 2, z: z0 - 1.5, facing: Math.PI,
            health: C.WINDOW_HEALTH, broken: false,
          });
        }
        if (rnd() < 0.5) {
          props.push({
            model: 'dumpster', rot: rnd() * 6.28, size: 2.2,
            x: x0 + 2 + rnd() * (inner - 4), z: z0 + inner + 2.5
          });
        }
        if (rnd() < 0.45) {
          chests.push({
            x: x0 + 3 + rnd() * (inner - 6), z: z0 + inner + 2.2,
            rot: rnd() * 6.28, opened: false,
          });
        }
      }
    }

    // Street lighting on every corner, and lamps down the long roads.
    for (var gj = 0; gj <= C.BLOCKS; gj++) {
      for (var gi = 0; gi <= C.BLOCKS; gi++) {
        var ix = gi * C.BLOCK, iz = gj * C.BLOCK;
        props.push({ model: 'traffic-light', x: ix - C.HALF_ROAD - 1.2, z: iz - C.HALF_ROAD - 1.2, rot: 0, size: 5 });
        if (gi < C.BLOCKS) props.push({ model: 'streetlight', x: ix + C.BLOCK / 2, z: iz - C.HALF_ROAD - 1, rot: 0, size: 6 });
        if (gj < C.BLOCKS) props.push({ model: 'streetlight', x: ix - C.HALF_ROAD - 1, z: iz + C.BLOCK / 2, rot: Math.PI / 2, size: 6 });
      }
    }

    // Interiors are real rooms in the same world, parked west of town where
    // nothing else is built. You are teleported in through a building's door
    // and back out by stepping on the mat inside it.
    //
    // Sealed on all four sides deliberately: when a room had a doorway you
    // could walk out of it into open nothing while the game still believed you
    // were indoors.
    function makeRoom(x0, z0, w, d, wallHeight) {
      var T = 0.9;
      var midZ = z0 + d / 2;
      var made = {
        room: { x0: x0, z0: z0, w: w, d: d, wall: wallHeight },
        spawn: { x: x0 + w - 6, z: midZ },
        exitAt: { x: x0 + w - 1.2, z: midZ },
        walls: [
          { x0: x0 - T, z0: z0 - T, x1: x0, z1: z0 + d + T },
          { x0: x0 - T, z0: z0 - T, x1: x0 + w + T, z1: z0 },
          { x0: x0 - T, z0: z0 + d, x1: x0 + w + T, z1: z0 + d + T },
          { x0: x0 + w, z0: z0 - T, x1: x0 + w + T, z1: z0 + d + T },
        ],
        exitZone: { x0: x0 + w - 3, z0: midZ - 2.2, x1: x0 + w - 0.4, z1: midZ + 2.2 },
        bounds: { x0: x0, z0: z0, x1: x0 + w, z1: z0 + d },
      };
      for (var i = 0; i < made.walls.length; i++) boxes.push(made.walls[i]);
      return made;
    }

    // The bank interior.
    var interior = makeRoom(-142, 158, 24, 20, 4.2);
    var room = interior.room;
    var midZ = room.z0 + room.d / 2;

    // The prize, at the back of the room.
    loot.push({
      kind: 'safe', cash: 5200, cool: 0, indoors: 'bank',
      x: room.x0 + 3.5, z: midZ, facing: -Math.PI / 2,
    });
    // Two tills along the side wall, worth grabbing on the way past.
    loot.push({ kind: 'register', cash: 480, cool: 0, indoors: 'bank',
      x: room.x0 + room.w / 2, z: room.z0 + 3, facing: Math.PI });
    loot.push({ kind: 'register', cash: 480, cool: 0, indoors: 'bank',
      x: room.x0 + room.w / 2, z: room.z0 + room.d - 3, facing: 0 });

    // One shared back room behind every forced door. You always come out of
    // the door you went in through, so it does not matter that they match.
    var hideout = makeRoom(-142, 108, 14, 12, 3.6);
    var den = hideout.room;

    chests.push({ x: den.x0 + 3, z: den.z0 + 3, rot: 0, opened: false, indoors: 'hideout' });
    chests.push({ x: den.x0 + 3, z: den.z0 + den.d - 3, rot: 0, opened: false, indoors: 'hideout' });
    chests.push({ x: den.x0 + den.w / 2, z: den.z0 + 2.5, rot: 0.4, opened: false, indoors: 'hideout' });

    // The big places get their own interiors: a department store floor and an
    // office lobby, both a good deal larger than a back room.
    var store = makeRoom(-210, 100, 34, 26, 5);
    var lobby = makeRoom(-210, 146, 22, 18, 4.6);

    // Shelves worth rifling through, and tills at the front.
    for (var sx = 0; sx < 4; sx++) {
      for (var sz = 0; sz < 3; sz++) {
        chests.push({
          x: store.room.x0 + 6 + sx * 7, z: store.room.z0 + 5 + sz * 8,
          rot: 0, opened: false, indoors: 'store',
        });
      }
    }
    loot.push({ kind: 'register', cash: 520, cool: 0, indoors: 'store',
      x: store.room.x0 + store.room.w - 5, z: store.room.z0 + 5, facing: Math.PI });
    loot.push({ kind: 'register', cash: 520, cool: 0, indoors: 'store',
      x: store.room.x0 + store.room.w - 5, z: store.room.z0 + store.room.d - 5, facing: 0 });

    loot.push({ kind: 'safe', cash: 1400, cool: 0, indoors: 'lobby',
      x: lobby.room.x0 + 3.5, z: lobby.room.z0 + lobby.room.d / 2, facing: -Math.PI / 2 });
    chests.push({ x: lobby.room.x0 + 6, z: lobby.room.z0 + 3.5, rot: 0, opened: false, indoors: 'lobby' });
    chests.push({ x: lobby.room.x0 + 6, z: lobby.room.z0 + lobby.room.d - 3.5, rot: 0, opened: false, indoors: 'lobby' });

    var rooms = { bank: interior, hideout: hideout, store: store, lobby: lobby };

    // Which interior a building leads to, by the model standing there.
    var INSIDE_OF = {
      'building-k': 'store', 'building-n': 'store',
      'tower-a': 'lobby', 'tower-c': 'lobby',
      'bank': 'bank',
    };

    // Every building gets a way in. The door goes on whichever face has clear
    // pavement in front of it, so nobody has to hunt for the one marked door.
    for (var bi = 0; bi < buildings.length; bi++) {
      var b = buildings[bi];
      if (b.model === 'bank') continue;              // already has its vault door
      var kind = INSIDE_OF[b.model] || 'hideout';
      var faces = [
        { x: b.x, z: b.z - b.d / 2 - 1.4, facing: Math.PI },
        { x: b.x, z: b.z + b.d / 2 + 1.4, facing: 0 },
        { x: b.x - b.w / 2 - 1.4, z: b.z, facing: Math.PI / 2 },
        { x: b.x + b.w / 2 + 1.4, z: b.z, facing: -Math.PI / 2 },
      ];
      for (var f = 0; f < faces.length; f++) {
        var spot = faces[f];
        var clear = true;
        for (var probe = 1.2; probe <= 3.2 && clear; probe += 1) {
          var px = spot.x + Math.sin(spot.facing) * probe;
          var pz = spot.z + Math.cos(spot.facing) * probe;
          for (var bx = 0; bx < boxes.length; bx++) {
            var solid = boxes[bx];
            if (px > solid.x0 - 0.6 && px < solid.x1 + 0.6 &&
                pz > solid.z0 - 0.6 && pz < solid.z1 + 0.6) { clear = false; break; }
          }
        }
        if (!clear) continue;
        doors.push({ kind: 'building', room: kind, x: spot.x, z: spot.z, facing: spot.facing });
        break;
      }
    }

    // Armouries: shopfronts on the pavement where you spend what you steal.
    var stores = [
      { x: C.BLOCK * 3 + 14, z: C.BLOCK * 3 - C.HALF_ROAD - 1.6, facing: Math.PI },
      { x: C.BLOCK * 1 - C.HALF_ROAD - 1.6, z: C.BLOCK * 5, facing: Math.PI / 2 },
      { x: C.BLOCK * 5 + 8, z: C.BLOCK * 1 + C.BLOCK - C.HALF_ROAD - 1.6, facing: 0 },
    ];

    // A wall around town so nobody drives off the edge of it.
    var lo = -C.HALF_ROAD - 4, hi = C.WORLD - C.HALF_ROAD + 4;
    boxes.push({ x0: lo - 6, z0: lo - 6, x1: lo, z1: hi + 6 });
    boxes.push({ x0: hi, z0: lo - 6, x1: hi + 6, z1: hi + 6 });
    boxes.push({ x0: lo - 6, z0: lo - 6, x1: hi + 6, z1: lo });
    boxes.push({ x0: lo - 6, z0: hi, x1: hi + 6, z1: hi + 6 });

    return {
      boxes: boxes, buildings: buildings, loot: loot,
      guns: guns, props: props, blocks: blockInfo,
      doors: doors, windows: windows, chests: chests, rooms: rooms,
      interior: interior, hideout: hideout, stores: stores
    };
  }

  // Roads run along every multiple of BLOCK, in both directions.
  function onRoad(x, z) {
    return nearLine(x) || nearLine(z);
  }
  function nearLine(v) {
    var k = Math.round(v / C.BLOCK);
    if (k < 0 || k > C.BLOCKS) return false;
    return Math.abs(v - k * C.BLOCK) <= C.HALF_ROAD;
  }

  function createGame(options) {
    options = options || {};
    var rnd = mulberry32(options.seed == null ? 20260823 : options.seed);
    var city = buildCity(rnd);

    var grid = {};
    var CELL = C.BLOCK;
    for (var b = 0; b < city.boxes.length; b++) {
      var box = city.boxes[b];
      for (var gz = Math.floor(box.z0 / CELL); gz <= Math.floor(box.z1 / CELL); gz++) {
        for (var gx = Math.floor(box.x0 / CELL); gx <= Math.floor(box.x1 / CELL); gx++) {
          var k = gx + ':' + gz;
          (grid[k] || (grid[k] = [])).push(b);
        }
      }
    }

    function blocked(x, z, r) {
      for (var gz = Math.floor((z - r) / CELL); gz <= Math.floor((z + r) / CELL); gz++) {
        for (var gx = Math.floor((x - r) / CELL); gx <= Math.floor((x + r) / CELL); gx++) {
          var list = grid[gx + ':' + gz];
          if (!list) continue;
          for (var i = 0; i < list.length; i++) {
            var s = city.boxes[list[i]];
            if (x + r > s.x0 && x - r < s.x1 && z + r > s.z0 && z - r < s.z1) return true;
          }
        }
      }
      return false;
    }

    var spawnX = C.BLOCK * 3;
    var spawnZ = C.BLOCK * 3;

    var state = {
      t: 0,
      seed: options.seed == null ? 20260823 : options.seed,
      city: city,
      player: {
        x: spawnX, z: spawnZ, yaw: 0, pitch: 0,
        health: C.MAX_HEALTH, money: 0,
        driving: false, car: null,
        hasGun: false, ammo: 0,
        weapon: null, owned: {}, ammoFor: {}, medkits: 0,
        xp: 0, level: 1, perks: {}, maxHealth: C.MAX_HEALTH,
        indoors: false,
        fireCooldown: 0, hurtAt: -99, meleeAt: -99, robbing: 0, robTarget: null,
        forcing: 0, forceTarget: null,
        soaked: false, soakTimer: 0, bob: 0,
        y: 0, vy: 0, onGround: true, runTimer: 0
      },
      cars: [],
      cops: [],
      civilians: [],
      darts: [],
      wanted: 0,
      wantedDecay: 0,
      events: [],
      timeOfDay: 0.28,                    // starts mid-morning
      store: { open: false, items: storeStock(), at: null },
      stats: { robbed: 0, copsDropped: 0, copsRunOver: 0, carsStolen: 0, timesSoaked: 0,
        brokeIn: 0, civiliansHelped: 0, chestsOpened: 0 },
    };

    // --- traffic and parked cars ---------------------------------------------

    function laneSpot(axis, line, along, dir) {
      // Right-hand traffic: offset half a lane from the centre line.
      var off = 4.4 * dir;
      return axis === 'x'
        ? { x: along, z: line + off }
        : { x: line - off, z: along };
    }

    function spawnTraffic(n) {
      for (var i = 0; i < n; i++) {
        var axis = rnd() < 0.5 ? 'x' : 'z';
        var line = (1 + Math.floor(rnd() * (C.BLOCKS - 1))) * C.BLOCK;
        var dir = rnd() < 0.5 ? 1 : -1;
        var along = 20 + rnd() * (C.WORLD - 40);
        var p = laneSpot(axis, line, along, dir);
        state.cars.push({
          x: p.x, z: p.z, angle: headingFor(axis, dir), speed: 8 + rnd() * 8,
          axis: axis, line: line, dir: dir, cruise: 9 + rnd() * 8,
          kind: 'civilian', ai: true, parked: false,
          model: CAR_MODELS[Math.floor(rnd() * CAR_MODELS.length)],
          health: 100, siren: 0
        });
      }
    }

    function spawnParked(n) {
      for (var i = 0; i < n; i++) {
        var axis = rnd() < 0.5 ? 'x' : 'z';
        var line = Math.floor(rnd() * (C.BLOCKS + 1)) * C.BLOCK;
        var dir = rnd() < 0.5 ? 1 : -1;
        var along = 15 + rnd() * (C.WORLD - 30);
        var p = laneSpot(axis, line, along, dir);
        if (blocked(p.x, p.z, C.CAR_R)) continue;
        state.cars.push({
          x: p.x, z: p.z, angle: headingFor(axis, dir), speed: 0,
          axis: axis, line: line, dir: dir, cruise: 0,
          kind: 'civilian', ai: false, parked: true,
          model: CAR_MODELS[Math.floor(rnd() * CAR_MODELS.length)],
          health: 100, siren: 0
        });
      }
      // Always one on the kerb where you start, so the game opens with a car.
      state.cars.push({
        x: spawnX + 6, z: spawnZ + 4.4, angle: headingFor('x', 1), speed: 0,
        axis: 'x', line: spawnZ, dir: 1, cruise: 0,
        kind: 'civilian', ai: false, parked: true,
        model: CAR_MODELS[0], health: 100, siren: 0
      });
    }

    function headingFor(axis, dir) {
      if (axis === 'x') return dir > 0 ? -Math.PI / 2 : Math.PI / 2;
      return dir > 0 ? Math.PI : 0;
    }

    spawnTraffic(14);
    spawnParked(12);

    // --- helpers --------------------------------------------------------------

    function say(text, seconds) {
      state.events.push({ text: text, life: seconds || 2.4 });
      if (state.events.length > 6) state.events.shift();
    }

    function awardXp(amount, reason) {
      var p = state.player;
      p.xp += amount;
      var want = Math.floor(p.xp / C.XP_PER_LEVEL) + 1;
      while (p.level < want) {
        p.level++;
        say('LEVEL ' + p.level, 3);
        for (var i = 0; i < PERKS.length; i++) {
          if (PERKS[i].level !== p.level || p.perks[PERKS[i].id]) continue;
          p.perks[PERKS[i].id] = true;
          say('unlocked: ' + PERKS[i].name + ' — ' + PERKS[i].blurb, 4.5);
          if (PERKS[i].id === 'tough') {
            p.maxHealth = C.MAX_HEALTH + 40;
            p.health = p.maxHealth;
          }
        }
      }
      if (reason) state.lastXp = { amount: amount, reason: reason, at: state.t };
    }

    function raiseWanted(n) {
      state.wanted = Math.min(C.MAX_WANTED, state.wanted + n);
      state.wantedDecay = C.WANTED_DECAY;
    }

    function playerPos() {
      var p = state.player;
      if (p.driving && p.car) return { x: p.car.x, z: p.car.z };
      return { x: p.x, z: p.z };
    }

    function nearestLoot() {
      var pos = playerPos(), best = null, bestD = Infinity;
      var inside = state.player.indoors || false;
      for (var i = 0; i < city.loot.length; i++) {
        var l = city.loot[i];
        if ((l.indoors || false) !== inside) continue;   // never point through a wall
        var d = dist(pos.x, pos.z, l.x, l.z);
        if (d < bestD) { bestD = d; best = l; }
      }
      return { loot: best, d: bestD };
    }

    function nearestCar() {
      var pos = playerPos(), best = null, bestD = Infinity;
      for (var i = 0; i < state.cars.length; i++) {
        var c = state.cars[i];
        if (c === state.player.car) continue;
        var d = dist(pos.x, pos.z, c.x, c.z);
        if (d < bestD) { bestD = d; best = c; }
      }
      return { car: best, d: bestD };
    }

    // --- movement -------------------------------------------------------------

    function moveOnFoot(dt, input) {
      var p = state.player;

      // Arrow left/right turn you on the spot; A and D strafe. Turning with
      // the keyboard matters for anyone who cannot aim with a mouse yet.
      var turn = (input.turnLeft ? 1 : 0) - (input.turnRight ? 1 : 0);
      if (turn) p.yaw += turn * C.TURN_SPEED * dt;

      // Jumping. Purely vertical: you cannot get onto anything with it, but it
      // feels much better than being glued to the pavement.
      if (input.jump && p.onGround) {
        p.vy = C.JUMP_SPEED;
        p.onGround = false;
      }
      if (!p.onGround) {
        p.vy -= C.GRAVITY * dt;
        p.y += p.vy * dt;
        if (p.y <= 0) { p.y = 0; p.vy = 0; p.onGround = true; }
      }

      var fx = forwardX(p.yaw), fz = forwardZ(p.yaw);
      var rx = -fz, rz = fx;                       // right-hand vector
      var mx = 0, mz = 0;
      if (input.forward) { mx += fx; mz += fz; }
      if (input.back) { mx -= fx; mz -= fz; }
      if (input.right) { mx += rx; mz += rz; }
      if (input.left) { mx -= rx; mz -= rz; }

      var len = Math.hypot(mx, mz);
      if (len > 0) {
        mx /= len; mz /= len;
        // Sprint on its own after a moment of running forward. Shift plus W
        // plus an arrow key is three keys at once, and plenty of laptop
        // keyboards simply will not report the third one.
        if (input.forward && !input.back) p.runTimer += dt; else p.runTimer = 0;
        var running = input.sprint || p.runTimer > C.AUTO_SPRINT_AFTER;
        var speed = running ? (p.perks.runner ? C.SPRINT * 1.25 : C.SPRINT) : C.WALK;
        p.bob += dt * speed;
        var nx = p.x + mx * speed * dt;
        if (!blocked(nx, p.z, C.PLAYER_R)) p.x = nx;
        var nz = p.z + mz * speed * dt;
        if (!blocked(p.x, nz, C.PLAYER_R)) p.z = nz;
      } else {
        // Standing still drops you back to a walk. Without this you sprint for
        // ever after one run.
        p.runTimer = 0;
      }
    }

    function driveCar(dt, input) {
      var p = state.player, car = p.car;
      if (input.forward) car.speed += C.CAR_ACCEL * dt;
      else if (input.back) car.speed -= C.CAR_BRAKE * dt;
      car.speed -= car.speed * C.CAR_DRAG * dt;
      car.speed = clamp(car.speed, -10, C.CAR_MAX);

      var steer = ((input.left || input.turnLeft) ? 1 : 0) - ((input.right || input.turnRight) ? 1 : 0);
      // Steering used to scale straight off speed, so a car crawling out of a
      // parking space would not turn at all. Keep some authority at low speed,
      // and flip it in reverse the way a real car behaves.
      var grip = 0.45 + 0.55 * Math.min(1, Math.abs(car.speed) / C.CAR_MAX);
      if (Math.abs(car.speed) > 0.4) {
        car.angle += steer * C.CAR_TURN * grip * dt * (car.speed < 0 ? -1 : 1) * 2.2;
      }

      // Resolve each axis on its own so a car scrapes along a wall instead of
      // wedging on it. Bouncing off both axes at once is what made kerbs sticky.
      var nx = car.x + forwardX(car.angle) * car.speed * dt;
      var nz = car.z + forwardZ(car.angle) * car.speed * dt;
      var freeX = !blocked(nx, car.z, C.CAR_R);
      var freeZ = !blocked(car.x, nz, C.CAR_R);
      if (freeX) car.x = nx;
      if (freeZ) car.z = nz;
      if (!freeX && !freeZ) car.speed *= -0.2;          // square on, bounce back
      // A glancing scrape costs speed at a steady rate rather than a fixed cut
      // per frame — compounded 60 times a second that stopped the car dead.
      else if (!freeX || !freeZ) car.speed *= Math.pow(0.7, dt);

      // Running an officer over knocks them down and brings the cavalry.
      if (Math.abs(car.speed) > C.RUN_OVER_SPEED) {
        for (var k = 0; k < state.cops.length; k++) {
          var hit = state.cops[k];
          if (hit.state === 'sat') continue;
          if (dist(car.x, car.z, hit.x, hit.z) > 2.5) continue;
          hit.state = 'sat';
          hit.sat = 10;
          state.stats.copsRunOver++;
          raiseWanted(2);
          say('you flattened an officer — now they are really cross', 2.8);
          city.guns.push({ x: hit.x, z: hit.z, taken: false });
        }
      }

      p.x = car.x; p.z = car.z;
      // Aim and the chase camera follow the car, so darts go where you drive.
      p.yaw = car.angle;
    }

    function updateTraffic(dt) {
      for (var i = 0; i < state.cars.length; i++) {
        var car = state.cars[i];
        if (!car.ai || car === state.player.car) continue;

        if (car.kind === 'police') { chaseWithCar(car, dt); continue; }

        car.speed += (car.cruise - car.speed) * Math.min(1, dt * 1.5);
        var along = car.axis === 'x' ? car.x : car.z;
        var next = along + car.dir * car.speed * dt;
        var k = car.dir > 0 ? Math.ceil(along / C.BLOCK) : Math.floor(along / C.BLOCK);
        var cross = k * C.BLOCK;
        var passing = car.dir > 0 ? next >= cross : next <= cross;

        if (passing && cross >= 0 && cross <= C.WORLD) {
          var forced = cross <= 0 || cross >= C.WORLD;
          if (forced || rnd() < 0.35) {
            var oldLine = car.line;
            car.axis = car.axis === 'x' ? 'z' : 'x';
            car.line = cross;
            car.dir = rnd() < 0.5 ? 1 : -1;
            var spot = laneSpot(car.axis, car.line, oldLine, car.dir);
            car.x = spot.x; car.z = spot.z;
            car.angle = headingFor(car.axis, car.dir);
            car.speed *= 0.6;
            continue;
          }
        }
        if (next < -C.HALF_ROAD || next > C.WORLD + C.HALF_ROAD) { car.dir *= -1; continue; }

        var lane = laneSpot(car.axis, car.line, next, car.dir);
        car.x += (lane.x - car.x) * Math.min(1, dt * 5);
        car.z += (lane.z - car.z) * Math.min(1, dt * 5);
        if (car.axis === 'x') car.x = next; else car.z = next;
        car.angle = headingFor(car.axis, car.dir);
      }
    }

    // Police cars drive straight at you and give up gracefully on walls.
    function chaseWithCar(car, dt) {
      var pos = playerPos();
      var want = Math.atan2(-(pos.x - car.x), -(pos.z - car.z));
      var diff = ((want - car.angle + Math.PI * 3) % (Math.PI * 2)) - Math.PI;
      car.angle += clamp(diff, -C.CAR_TURN * dt * 2, C.CAR_TURN * dt * 2);

      var gap = dist(pos.x, pos.z, car.x, car.z);
      // On foot they hang back rather than driving onto the pavement at you.
      var standoff = state.player.driving ? 0 : C.FOOT_CAR_STANDOFF;
      var target = gap < standoff ? 0 : (gap > 16 ? 22 : 8);
      car.speed += (target - car.speed) * Math.min(1, dt * 1.2);
      car.siren += dt;

      var nx = car.x + forwardX(car.angle) * car.speed * dt;
      var nz = car.z + forwardZ(car.angle) * car.speed * dt;
      if (!blocked(nx, nz, C.CAR_R)) { car.x = nx; car.z = nz; }
      else { car.speed *= -0.2; car.angle += 0.6 * dt * 4; }

      // Close enough: the officers get out and continue on foot.
      if (gap < (state.player.driving ? 18 : C.FOOT_CAR_STANDOFF + 4) && !car.emptied) {
        car.emptied = true;
        spawnCop(car.x + 2.2, car.z + 2.2);
        if (state.wanted >= 3) spawnCop(car.x - 2.2, car.z - 2.2);
      }
    }

    // --- police ----------------------------------------------------------------

    // Officers still on their feet. Downed ones are scenery, not opposition.
    function standingCops() {
      var n = 0;
      for (var i = 0; i < state.cops.length; i++) if (state.cops[i].state !== 'sat') n++;
      return n;
    }

    function spawnCop(x, z) {
      if (standingCops() >= C.MAX_COPS) return null;
      var cop = {
        x: x, z: z, health: C.COP_HEALTH, cooldown: 0.8 + rnd() * 0.8,
        state: 'chase', sat: 0, bob: rnd() * 6,
        // Some turn up without a blaster. They still chase you, but all they
        // can do is grab at you when they get close.
        armed: rnd() < C.COP_ARMED_SHARE,
        hitAt: -99,
      };
      state.cops.push(cop);
      return cop;
    }

    function spawnPoliceCar() {
      var count = 0;
      for (var i = 0; i < state.cars.length; i++) if (state.cars[i].kind === 'police') count++;
      // One car per star when you are driving. On foot they are far more
      // intimidating than they need to be, so only one comes unless the whole
      // force is out.
      var allowed = state.player.driving
        ? Math.min(C.MAX_POLICE_CARS, state.wanted)
        : (state.wanted >= 4 ? 2 : C.FOOT_POLICE_CARS);
      if (count >= allowed) return;

      var pos = playerPos();
      // Arrive along a road, from off in the distance.
      var axis = rnd() < 0.5 ? 'x' : 'z';
      var line = Math.round((axis === 'x' ? pos.z : pos.x) / C.BLOCK) * C.BLOCK;
      line = clamp(line, 0, C.WORLD);
      var dir = rnd() < 0.5 ? 1 : -1;
      var along = clamp((axis === 'x' ? pos.x : pos.z) - dir * 60, 5, C.WORLD - 5);
      var spot = laneSpot(axis, line, along, dir);
      state.cars.push({
        x: spot.x, z: spot.z, angle: headingFor(axis, dir), speed: 14,
        axis: axis, line: line, dir: dir, cruise: 20,
        kind: 'police', ai: true, parked: false, model: 'car-police',
        health: 100, siren: 0, emptied: false
      });
    }

    var copSpawnTimer = 0;
    var carSpawnTimer = 0;

    function updatePolice(dt) {
      var pos = playerPos();
      var p = state.player;

      var hidden = !!p.indoors;
      if (state.wanted > 0) {
        state.wantedDecay -= dt * (hidden ? C.HIDEOUT_DECAY : 1) * (p.perks.ghost ? 2 : 1);
        if (state.wantedDecay <= 0) {
          state.wanted--;
          state.wantedDecay = C.WANTED_DECAY;
          if (state.wanted === 0) say('the police have lost interest', 3);
        }

        copSpawnTimer -= dt;
        if (!hidden && copSpawnTimer <= 0 && standingCops() < state.wanted + 1) {
          var ang = rnd() * Math.PI * 2;
          var d = 34 + rnd() * 18;
          var cx = clamp(pos.x + Math.cos(ang) * d, 4, C.WORLD - 4);
          var cz = clamp(pos.z + Math.sin(ang) * d, 4, C.WORLD - 4);
          if (!blocked(cx, cz, 0.8)) spawnCop(cx, cz);
          copSpawnTimer = 2.2;
        }

        carSpawnTimer -= dt;
        if (!hidden && carSpawnTimer <= 0) {
          spawnPoliceCar();
          carSpawnTimer = Math.max(3, 10 - state.wanted * 1.6);
        }
      } else {
        // Everyone goes home when the heat is off.
        for (var q = state.cops.length - 1; q >= 0; q--) {
          var going = state.cops[q];
          var far = dist(pos.x, pos.z, going.x, going.z);
          if (going.state === 'sat' ? far > C.DOWNED_FORGET : far > 45) state.cops.splice(q, 1);
        }
        for (var r = state.cars.length - 1; r >= 0; r--) {
          if (state.cars[r].kind === 'police' &&
              dist(pos.x, pos.z, state.cars[r].x, state.cars[r].z) > 55) state.cars.splice(r, 1);
        }
      }

      for (var i = state.cops.length - 1; i >= 0; i--) {
        var cop = state.cops[i];

        if (cop.state === 'sat') {
          // Stays down for good. Only cleaned up once you are nowhere near it,
          // so the streets do not fill with bodies you will never see again.
          if (dist(pos.x, pos.z, cop.x, cop.z) > C.DOWNED_FORGET) state.cops.splice(i, 1);
          continue;
        }

        var gap = dist(pos.x, pos.z, cop.x, cop.z);
        cop.bob += dt * 6;

        if (gap > C.COP_STANDOFF) {
          var dx = (pos.x - cop.x) / (gap || 1), dz = (pos.z - cop.z) / (gap || 1);
          var nx = cop.x + dx * C.COP_SPEED * dt;
          if (!blocked(nx, cop.z, 0.6)) cop.x = nx;
          var nz = cop.z + dz * C.COP_SPEED * dt;
          if (!blocked(cop.x, nz, 0.6)) cop.z = nz;
        }

        cop.cooldown -= dt;
        var canAct = !p.soaked && !p.indoors && !state.store.open;
        if (cop.armed) {
          if (gap < C.COP_RANGE && cop.cooldown <= 0 && canAct) {
            cop.cooldown = C.COP_FIRE_DELAY;
            fireDart(cop.x, 1.4, cop.z, pos.x, p.driving ? 1.0 : 1.3, pos.z,
              C.COP_DART_SPEED, 'police', C.COP_DART_DAMAGE, 0.16);
          }
        } else if (gap < C.COP_GRAB_RANGE && cop.cooldown <= 0 && canAct) {
          // Empty handed: all they can do is make a grab for you.
          cop.cooldown = C.COP_GRAB_DELAY;
          hurtPlayer(C.COP_GRAB_DAMAGE);
        }
      }
    }

    // --- the public ------------------------------------------------------------
    //
    // People wander the streets. When the police turn up most of them bolt, but
    // a few decide they are on your side and start throwing darts of their own.

    function spawnCivilian() {
      var pos = playerPos();
      for (var attempt = 0; attempt < 14; attempt++) {
        var ang = rnd() * Math.PI * 2;
        var away = 22 + rnd() * 26;
        var x = clamp(pos.x + Math.cos(ang) * away, 4, C.WORLD - 4);
        var z = clamp(pos.z + Math.sin(ang) * away, 4, C.WORLD - 4);
        if (blocked(x, z, 0.7)) continue;
        var person = {
          x: x, z: z, yaw: rnd() * 6.28, health: C.CIV_HEALTH,
          state: 'wander', isCivilian: true, brave: rnd() < C.CIV_BRAVE,
          model: CIVILIAN_MODELS[Math.floor(rnd() * CIVILIAN_MODELS.length)],
          hitAt: -99,
          cooldown: rnd() * 2, bob: rnd() * 6, target: null, repath: 0,
          stuck: 0, pause: 0,
        };
        state.civilians.push(person);
        return person;
      }
      return null;
    }

    function hurtCivilian(person, amount, source) {
      if (person.state === 'sat') return;
      person.health -= amount;
      person.hitAt = state.t;
      if (source === 'player' && state.wanted < 2) raiseWanted(1);
      if (person.health <= 0) {
        person.state = 'sat';
        if (source === 'player') say('that was a member of the public', 2.2);
      }
    }

    function nearestStandingCop(x, z) {
      var best = null, bestD = Infinity;
      for (var i = 0; i < state.cops.length; i++) {
        var cop = state.cops[i];
        if (cop.state === 'sat') continue;
        var d = dist(x, z, cop.x, cop.z);
        if (d < bestD) { bestD = d; best = cop; }
      }
      return { cop: best, d: bestD };
    }

    function stepPerson(person, dx, dz, speed, dt) {
      var len = Math.hypot(dx, dz);
      // Below about a third of a metre the direction is mostly noise, and
      // turning to face it is what made people spin on the spot.
      if (len < 0.35) return;
      dx /= len; dz /= len;

      // Turn towards the heading at a human rate rather than snapping to it.
      var want = yawTowards(dx, dz);
      var diff = ((want - person.yaw + Math.PI * 3) % (Math.PI * 2)) - Math.PI;
      person.yaw += clamp(diff, -C.CIV_TURN * dt, C.CIV_TURN * dt);

      person.bob += dt * speed;
      var nx = person.x + dx * speed * dt;
      var freeX = !blocked(nx, person.z, 0.6);
      if (freeX) person.x = nx;
      var nz = person.z + dz * speed * dt;
      var freeZ = !blocked(person.x, nz, 0.6);
      if (freeZ) person.z = nz;

      // Walked into something: pick a new way, but not more than once a second
      // or they twitch between choices every frame.
      if (!freeX && !freeZ) person.repath = Math.min(person.repath, 0);
      person.stuck = (!freeX && !freeZ) ? (person.stuck || 0) + dt : 0;
    }

    function updateCivilians(dt) {
      var pos = playerPos();

      // Keep a few about, near enough to matter, and tidy away the far ones.
      var standing = 0;
      for (var c = state.civilians.length - 1; c >= 0; c--) {
        var far = dist(pos.x, pos.z, state.civilians[c].x, state.civilians[c].z);
        var down = state.civilians[c].state === 'sat';
        if (down ? far > C.DOWNED_FORGET : far > 110) { state.civilians.splice(c, 1); continue; }
        if (!down) standing++;
      }
      if (standing < C.CIVILIANS && !state.player.indoors) spawnCivilian();

      for (var i = 0; i < state.civilians.length; i++) {
        var person = state.civilians[i];
        if (person.state === 'sat') continue;

        var near = nearestStandingCop(person.x, person.z);
        var trouble = state.wanted > 0 && near.cop && near.d < 30;

        if (trouble && person.brave) {
          person.state = 'fight';
          // Close to a sensible range, then start throwing darts.
          if (near.d > C.CIV_RANGE * 0.7) {
            stepPerson(person, near.cop.x - person.x, near.cop.z - person.z, C.CIV_SPEED, dt);
          } else {
            // Holding position: turn to face them, but at a human rate.
            var face = yawTowards(near.cop.x - person.x, near.cop.z - person.z);
            var off = ((face - person.yaw + Math.PI * 3) % (Math.PI * 2)) - Math.PI;
            person.yaw += clamp(off, -C.CIV_TURN * dt, C.CIV_TURN * dt);
          }
          person.cooldown -= dt;
          if (person.cooldown <= 0 && near.d < C.CIV_RANGE) {
            person.cooldown = C.CIV_FIRE_DELAY;
            fireDart(person.x, 1.3, person.z, near.cop.x, 1.4, near.cop.z,
              C.COP_DART_SPEED, 'civilian', C.CIV_DART_DAMAGE, 0.1);
          }
        } else if (trouble) {
          person.state = 'flee';
          var awayX = person.x - near.cop.x, awayZ = person.z - near.cop.z;
          if (Math.hypot(awayX, awayZ) < 0.5) {     // standing on top of them
            awayX = Math.cos(person.bob);
            awayZ = Math.sin(person.bob);
          }
          stepPerson(person, awayX * 4, awayZ * 4, C.CIV_FLEE_SPEED, dt);
        } else {
          person.state = 'wander';
          person.repath -= dt;

          var toX = person.target ? person.target.x - person.x : 0;
          var toZ = person.target ? person.target.z - person.z : 0;
          var left = person.target ? Math.hypot(toX, toZ) : 0;

          // Arrived, ran out of patience, or wedged: choose somewhere new. The
          // pause afterwards is what stops them jittering between choices.
          if (!person.target || person.repath <= 0 || left < 1.5 || person.stuck > 0.6) {
            var ang = rnd() * Math.PI * 2;
            person.target = {
              x: clamp(person.x + Math.cos(ang) * (10 + rnd() * 18), 3, C.WORLD - 3),
              z: clamp(person.z + Math.sin(ang) * (10 + rnd() * 18), 3, C.WORLD - 3),
            };
            person.repath = 4 + rnd() * 5;
            person.stuck = 0;
            person.pause = 0.4 + rnd() * 1.2;       // stand still a moment first
          }

          if (person.pause > 0) {
            person.pause -= dt;
            person.state = 'idle';
          } else if (left >= 1.5) {
            stepPerson(person, toX, toZ, C.CIV_SPEED, dt);
          }
        }
      }
    }

    // --- darts -----------------------------------------------------------------

    function fireDart(x, y, z, tx, ty, tz, speed, owner, damage, spread) {
      var dx = tx - x, dy = ty - y, dz = tz - z;
      var len = Math.hypot(dx, dy, dz) || 1;
      dx /= len; dy /= len; dz /= len;
      if (spread) {
        dx += (rnd() - 0.5) * spread;
        dy += (rnd() - 0.5) * spread * 0.5;
        dz += (rnd() - 0.5) * spread;
      }
      state.darts.push({
        x: x, y: y, z: z,
        vx: dx * speed, vy: dy * speed, vz: dz * speed,
        life: C.DART_LIFE, owner: owner, damage: damage
      });
    }

    function updateDarts(dt) {
      var p = state.player;
      var pos = playerPos();
      for (var i = state.darts.length - 1; i >= 0; i--) {
        var d = state.darts[i];
        var fromX = d.x, fromY = d.y, fromZ = d.z;
        d.life -= dt;
        d.vy -= 7 * dt;                                  // foam darts droop
        d.x += d.vx * dt; d.y += d.vy * dt; d.z += d.vz * dt;

        var lowY = Math.min(fromY, d.y), highY = Math.max(fromY, d.y);
        var gone = d.life <= 0 || d.y < 0.05 || blocked(d.x, d.z, 0.12);

        if (!gone && d.owner === 'police' && !p.soaked) {
          var hitR = p.driving ? 2.0 : 0.85;
          if (segmentDistance(fromX, fromZ, d.x, d.z, pos.x, pos.z) < hitR &&
              lowY < (p.driving ? 2.2 : 2.0 + p.y)) {
            hurtPlayer(d.damage);
            gone = true;
          }
        }
        // Darts from you or from a helpful bystander both trouble the police.
        if (!gone && (d.owner === 'player' || d.owner === 'civilian')) {
          for (var c = 0; c < state.cops.length; c++) {
            var cop = state.cops[c];
            if (cop.state === 'sat') continue;
            if (segmentDistance(fromX, fromZ, d.x, d.z, cop.x, cop.z) < C.COP_HIT_R &&
                highY > 0.2 && lowY < 2.4) {
              hurtCop(cop, d.damage);
              if (d.owner === 'civilian') state.stats.civiliansHelped++;
              gone = true;
              break;
            }
          }
        }
        if (!gone) {
          for (var wI = 0; wI < city.windows.length; wI++) {
            var pane = city.windows[wI];
            if (pane.broken) continue;
            if (segmentDistance(fromX, fromZ, d.x, d.z, pane.x, pane.z) > 1.3) continue;
            if (highY < 0.8 || lowY > 3.2) continue;
            pane.health -= d.damage;
            pane.hitAt = state.t;
            if (pane.health <= 0) {
              pane.broken = true;
              city.doors.push({ kind: 'hideout', x: pane.x, z: pane.z, facing: pane.facing, fromWindow: true });
              say('window smashed — you can climb in there now', 2.6);
              if (state.wanted < 1) raiseWanted(1);
            }
            gone = true;
            break;
          }
        }

        // Anyone can catch a stray. Police darts included.
        if (!gone && d.owner !== 'civilian') {
          for (var v = 0; v < state.civilians.length; v++) {
            var bystander = state.civilians[v];
            if (bystander.state === 'sat') continue;
            if (segmentDistance(fromX, fromZ, d.x, d.z, bystander.x, bystander.z) < C.COP_HIT_R &&
                highY > 0.2 && lowY < 2.4) {
              hurtCivilian(bystander, d.damage, d.owner);
              gone = true;
              break;
            }
          }
        }
        if (gone) state.darts.splice(i, 1);
      }
    }

    function hurtPlayer(amount, graceless) {
      var p = state.player;
      // Nobody can touch you while you are shopping or inside a building.
      if (!graceless && (p.indoors || state.store.open)) return;
      if (!graceless && state.t - p.hurtAt < C.HIT_GRACE) return;
      if (p.perks.nerves) amount *= 0.6;
      p.health = Math.max(0, p.health - amount);
      p.hurtAt = state.t;
      if (p.health <= 0 && !p.soaked) {
        p.soaked = true;
        p.soakTimer = 2.6;
        state.stats.timesSoaked++;
        say('SOAKED — you sit this one out for a moment', 3);
      }
    }

    function hurtCop(cop, amount) {
      if (cop.state === 'sat') return;
      cop.health -= amount;
      cop.hitAt = state.t;              // the renderer flashes them white
      if (cop.health <= 0) {
        cop.state = 'sat';
        state.stats.copsDropped++;
        awardXp(40, 'officer');
        say('officer is out of the fight', 2);
        // Only the ones who had a blaster leave one behind.
        if (cop.armed) city.guns.push({ x: cop.x, z: cop.z, taken: false });
      }
    }

    // --- actions ---------------------------------------------------------------

    function currentWeapon() {
      var p = state.player;
      return p.weapon ? weaponById(p.weapon) : null;
    }

    function tryShoot() {
      var p = state.player;
      var gun = currentWeapon();
      if (p.soaked || state.store.open || !gun) return false;
      if ((p.ammoFor[gun.id] || 0) <= 0 || p.fireCooldown > 0) return false;

      p.fireCooldown = gun.delay;
      p.ammoFor[gun.id]--;
      p.ammo = p.ammoFor[gun.id];

      var pos = playerPos();
      var eye = p.driving ? 1.2 : C.EYE + p.y;
      // A scatter blaster throws several darts at once; the rest throw one.
      for (var n = 0; n < (gun.pellets || 1); n++) {
        var yaw = p.yaw + (rnd() - 0.5) * gun.spread * 2;
        var pitch = p.pitch + (rnd() - 0.5) * gun.spread;
        var fx = forwardX(yaw) * Math.cos(pitch);
        var fz = forwardZ(yaw) * Math.cos(pitch);
        var fy = Math.sin(pitch);
        state.darts.push({
          x: pos.x + fx * 0.7, y: eye + fy * 0.7, z: pos.z + fz * 0.7,
          vx: fx * C.DART_SPEED, vy: fy * C.DART_SPEED, vz: fz * C.DART_SPEED,
          life: C.DART_LIFE, owner: 'player', damage: gun.damage
        });
      }
      // Shooting at the police is, understandably, a crime.
      if (state.wanted < 1) raiseWanted(1);
      return true;
    }

    // Bare hands. Not much reach, but it is always available.
    function tryMelee() {
      var p = state.player;
      if (p.soaked || state.store.open || p.driving || p.fireCooldown > 0) return false;
      p.fireCooldown = C.MELEE_DELAY;
      p.meleeAt = state.t;

      var pos = playerPos();
      var fx = forwardX(p.yaw), fz = forwardZ(p.yaw);
      var landed = false;

      // A door in front of you gives way to a shoulder rather than a fist.
      var door = nearestDoor();
      if (door.d < C.DOOR_RANGE && door.at && door.kind === 'in') {
        enterRoom(door.at);
        raiseWanted(1);
        say('you shouldered the door in', 2);
        return true;
      }

      var targets = state.cops.concat(state.civilians);
      for (var i = 0; i < targets.length; i++) {
        var who = targets[i];
        if (who.state === 'sat') continue;
        var dx = who.x - pos.x, dz = who.z - pos.z;
        var range = Math.hypot(dx, dz);
        if (range > C.MELEE_RANGE || range < 0.001) continue;
        // Only what is roughly in front of you.
        if (Math.acos(clamp((dx / range) * fx + (dz / range) * fz, -1, 1)) > C.MELEE_ARC) continue;
        if (who.isCivilian) hurtCivilian(who, C.MELEE_DAMAGE, 'player');
        else hurtCop(who, C.MELEE_DAMAGE);
        landed = true;
      }
      if (landed && state.wanted < 1) raiseWanted(1);
      return landed;
    }

    function giveWeapon(id, ammo) {
      var p = state.player;
      var gun = weaponById(id);
      p.owned[gun.id] = true;
      p.ammoFor[gun.id] = (p.ammoFor[gun.id] || 0) + (ammo == null ? gun.mag : ammo);
      p.weapon = gun.id;
      p.hasGun = true;
      p.ammo = p.ammoFor[gun.id];
      return gun;
    }

    // Picks a blaster straight off the inventory bar, by its number.
    function selectSlot(index) {
      var p = state.player;
      var mine = [];
      for (var i = 0; i < WEAPONS.length; i++) if (p.owned[WEAPONS[i].id]) mine.push(WEAPONS[i].id);
      if (index < 0 || index >= mine.length) return false;
      if (p.weapon === mine[index]) return false;
      p.weapon = mine[index];
      p.ammo = p.ammoFor[p.weapon] || 0;
      say('holding: ' + weaponById(p.weapon).name, 1.6);
      return true;
    }

    // Cycles through the blasters you actually own.
    function switchWeapon(step) {
      var p = state.player;
      var mine = [];
      for (var i = 0; i < WEAPONS.length; i++) if (p.owned[WEAPONS[i].id]) mine.push(WEAPONS[i].id);
      if (mine.length < 2) return false;
      var at = mine.indexOf(p.weapon);
      p.weapon = mine[(at + (step || 1) + mine.length) % mine.length];
      p.ammo = p.ammoFor[p.weapon] || 0;
      say('holding: ' + weaponById(p.weapon).name, 1.6);
      return true;
    }

    function useMedkit() {
      var p = state.player;
      if (p.medkits <= 0 || p.health >= C.MAX_HEALTH || p.soaked) return false;
      p.medkits--;
      p.health = Math.min(C.MAX_HEALTH, p.health + C.MEDKIT_HEAL);
      say('patched up (+' + C.MEDKIT_HEAL + ')', 1.8);
      return true;
    }

    function nearestChest() {
      var pos = playerPos(), best = null, bestD = Infinity;
      var inside = state.player.indoors || false;
      for (var i = 0; i < city.chests.length; i++) {
        var box = city.chests[i];
        if (box.opened || (box.indoors || false) !== inside) continue;
        var d = dist(pos.x, pos.z, box.x, box.z);
        if (d < bestD) { bestD = d; best = box; }
      }
      return { chest: best, d: bestD };
    }

    // Crates hold money, darts, med kits, or occasionally a blaster.
    function openChest(box) {
      var p = state.player;
      box.opened = true;
      box.openedAt = state.t;
      state.stats.chestsOpened++;
      awardXp(20, 'chest');

      var bonus = p.perks.scrounger ? 1.8 : 1;
      var roll = rnd();
      if (roll < 0.45) {
        var cash = Math.round((80 + rnd() * 220) * bonus);
        p.money += cash;
        say('found $' + cash + ' in the crate', 2.4);
        box.contained = 'money';
      } else if (roll < 0.72) {
        var held = currentWeapon() || weaponById('blaster');
        if (!p.owned[held.id]) giveWeapon(held.id, 0);
        var darts = Math.round(held.mag * 0.6 * bonus);
        p.ammoFor[held.id] = (p.ammoFor[held.id] || 0) + darts;
        p.ammo = p.ammoFor[p.weapon] || 0;
        say('found ' + darts + ' darts', 2.2);
        box.contained = 'ammo';
      } else if (roll < 0.9) {
        p.medkits++;
        say('found a med kit', 2.2);
        box.contained = 'medkit';
      } else {
        var prize = WEAPONS[1 + Math.floor(rnd() * (WEAPONS.length - 1))];
        giveWeapon(prize.id);
        say('a whole ' + prize.name + ' was in there', 3);
        box.contained = 'weapon';
      }
    }

    // What to draw across the top of the screen.
    function inventory() {
      var p = state.player;
      var slots = [];
      for (var i = 0; i < WEAPONS.length; i++) {
        if (!p.owned[WEAPONS[i].id]) continue;
        slots.push({
          kind: 'weapon', id: WEAPONS[i].id, label: WEAPONS[i].name,
          count: p.ammoFor[WEAPONS[i].id] || 0, active: p.weapon === WEAPONS[i].id,
        });
      }
      if (p.medkits > 0) slots.push({ kind: 'medkit', label: 'Med kit', count: p.medkits });
      return slots;
    }

    function nearestStore() {
      var pos = playerPos(), best = null, bestD = Infinity;
      for (var i = 0; i < city.stores.length; i++) {
        var st = city.stores[i];
        var d = dist(pos.x, pos.z, st.x, st.z);
        if (d < bestD) { bestD = d; best = st; }
      }
      return { store: best, d: bestD };
    }

    // The bank's front door: outside it takes you in, inside it takes you out.
    function nearestDoor() {
      var pos = playerPos();
      var p = state.player;
      if (p.indoors) {
        var e = city.rooms[p.indoors].exitAt;
        return { kind: 'out', d: dist(pos.x, pos.z, e.x, e.z) };
      }
      if (p.doorCooldown > 0) return { kind: 'in', d: Infinity, at: null };
      var best = null, bestD = Infinity;
      for (var i = 0; i < city.doors.length; i++) {
        var door = city.doors[i];
        var d = dist(pos.x, pos.z, door.x, door.z);
        if (d < bestD) { bestD = d; best = door; }
      }
      return { kind: 'in', d: bestD, at: best };
    }

    // One way in for every kind of building. The door says which room it leads
    // to; a department store gets a shop floor, a tower gets a lobby, and
    // everything else gets a back room.
    function enterRoom(door) {
      var p = state.player;
      var key = door.kind === 'bank' ? 'bank' : (door.room || 'hideout');
      var room = city.rooms[key];
      if (!room) return false;
      p.indoors = key;
      p.doorCooldown = 1.2;
      p.returnTo = {
        x: door.x + Math.sin(door.facing) * 2.4,
        z: door.z + Math.cos(door.facing) * 2.4,
      };
      p.x = room.spawn.x;
      p.z = room.spawn.z;
      p.yaw = Math.PI / 2;                          // facing into the room
      var what = key === 'bank' ? 'the bank — the safe is at the back'
        : key === 'store' ? 'a department store — plenty to rifle through'
        : key === 'lobby' ? 'an office lobby' : 'a back room';
      say('inside ' + what, 3);
      return true;
    }

    function leaveRoom() {
      var p = state.player;
      p.indoors = false;
      p.doorCooldown = 1.2;
      var back = p.returnTo || { x: spawnX, z: spawnZ };
      p.x = back.x;
      p.z = back.z;
      say('back outside', 1.6);
    }

    function buy(index) {
      var p = state.player;
      var item = state.store.items[index];
      if (!item) return 'none';
      if (p.money < item.price) { say('not enough money for the ' + item.name, 2); return 'poor'; }

      if (item.kind === 'weapon') {
        if (p.owned[item.weapon]) {
          var gun = weaponById(item.weapon);
          p.money -= item.price;
          p.ammoFor[gun.id] += gun.mag;
          p.weapon = gun.id;
          p.ammo = p.ammoFor[gun.id];
          say('another magazine for the ' + gun.name, 2);
          return 'ammo';
        }
        p.money -= item.price;
        giveWeapon(item.weapon);
        say('bought the ' + item.name, 2.2);
        return 'weapon';
      }
      if (item.kind === 'ammo') {
        var held = currentWeapon();
        if (!held) { say('nothing to load — buy a blaster first', 2); return 'none'; }
        p.money -= item.price;
        p.ammoFor[held.id] += held.mag;
        p.ammo = p.ammoFor[held.id];
        say('+' + held.mag + ' darts', 1.8);
        return 'ammo';
      }
      if (item.kind === 'medkit') {
        p.money -= item.price;
        p.medkits++;
        say('med kit bought — press H to use it', 2.4);
        return 'medkit';
      }
      return 'none';
    }

    // E is the only interaction key: it does whatever you are standing next to.
    function interact() {
      var p = state.player;
      if (p.soaked) return 'none';

      if (state.store.open) {
        state.store.open = false;
        state.store.at = null;
        return 'store-close';
      }

      if (p.driving) {
        var car = p.car;
        car.speed = 0;
        if (car.kind === 'civilian') { car.ai = true; car.parked = true; }
        p.driving = false;
        p.car = null;
        p.x = car.x + 2.6;
        p.z = car.z + 2.6;
        say('out of the car', 1.4);
        return 'exit';
      }

      var box = nearestChest();
      if (box.chest && box.d < C.CHEST_RANGE) {
        openChest(box.chest);
        return 'chest';
      }

      // Shop first: you stand right next to the counter to use it.
      var shop = nearestStore();
      if (shop.store && shop.d < C.STORE_RANGE) {
        state.store.open = !state.store.open;
        state.store.at = state.store.open ? shop.store : null;
        if (state.store.open) say('armoury — press a number to buy, E to leave', 3);
        return state.store.open ? 'store' : 'store-close';
      }

      var gun = nearestGun();
      if (gun.gun && gun.d < C.PICKUP_RANGE) {
        gun.gun.taken = true;
        var picked = giveWeapon('blaster');
        say('picked up a ' + picked.name + ' — click or press S to fire', 2.8);
        return 'gun';
      }

      var near = nearestLoot();
      if (near.loot && near.d < C.ROB_RANGE) {
        if (near.loot.cool > 0) { say('this one is empty for now', 1.6); return 'empty'; }
        p.robTarget = near.loot;
        p.robbing = 0.0001;                         // held-E progress starts
        return 'rob';
      }

      var door = nearestDoor();
      if (door.d < C.DOOR_RANGE) {
        if (door.kind === 'out') { leaveRoom(); return 'leave'; }
        if (door.at) { enterRoom(door.at); return 'enter'; }
      }

      var found = nearestCar();
      if (found.car && found.d < C.ENTER_RANGE) {
        p.driving = true;
        p.car = found.car;
        found.car.ai = false;
        found.car.parked = false;
        found.car.emptied = true;
        if (found.car.kind === 'police') say('you are now driving: A POLICE CAR', 2.6);
        else say('you are now driving: A CAR', 2.2);
        state.stats.carsStolen++;
        awardXp(15, 'car');
        // Taking someone's car in front of them is noticed.
        raiseWanted(1);
        return 'enter';
      }
      return 'none';
    }

    // Blasters and ammo are picked up simply by walking over them.
    function updateGroundPickups() {
      var p = state.player;
      if (p.driving || p.soaked) return;
      var pos = playerPos();
      for (var i = 0; i < city.guns.length; i++) {
        var lying = city.guns[i];
        if (lying.taken) continue;
        if (lying.cool > 0) { lying.cool -= 1 / 60; continue; }
        if (dist(pos.x, pos.z, lying.x, lying.z) > C.PICKUP_RANGE) continue;
        lying.taken = true;
        var id = lying.weapon || 'blaster';
        var already = p.owned[id];
        var gun = giveWeapon(id, lying.ammo);
        say(already ? '+' + (lying.ammo == null ? gun.mag : lying.ammo) + ' darts'
                    : 'picked up a ' + gun.name, 2);
      }
    }

    // Puts your current blaster on the pavement, ammo and all.
    function dropWeapon() {
      var p = state.player;
      var gun = currentWeapon();
      if (!gun || p.driving) return false;
      var pos = playerPos();
      city.guns.push({
        x: pos.x + forwardX(p.yaw) * C.DROP_RANGE,
        z: pos.z + forwardZ(p.yaw) * C.DROP_RANGE,
        taken: false, weapon: gun.id, ammo: p.ammoFor[gun.id] || 0,
        // Do not hoover it straight back up on the next step.
        cool: 1.2,
      });
      p.owned[gun.id] = false;
      p.ammoFor[gun.id] = 0;
      p.weapon = null;
      for (var i = 0; i < WEAPONS.length; i++) {
        if (p.owned[WEAPONS[i].id]) { p.weapon = WEAPONS[i].id; break; }
      }
      p.hasGun = !!p.weapon;
      p.ammo = p.weapon ? p.ammoFor[p.weapon] : 0;
      say('dropped the ' + gun.name, 1.8);
      return true;
    }

    function nearestGun() {
      var pos = playerPos(), best = null, bestD = Infinity;
      for (var i = 0; i < city.guns.length; i++) {
        var g = city.guns[i];
        if (g.taken) continue;
        var d = dist(pos.x, pos.z, g.x, g.z);
        if (d < bestD) { bestD = d; best = g; }
      }
      return { gun: best, d: bestD };
    }

    // Shouldering a door open. Same hold-to-do-it feel as a robbery.
    function updateBreakIn(dt, input) {
      var p = state.player;
      if (!p.forceTarget) return;
      var pos = playerPos();
      if (!input.interact || dist(pos.x, pos.z, p.forceTarget.x, p.forceTarget.z) > C.DOOR_RANGE || p.soaked) {
        p.forcing = 0;
        p.forceTarget = null;
        return;
      }
      p.forcing += dt;
      if (p.forcing >= C.BREAK_IN_TIME) {
        var door = p.forceTarget;
        p.forcing = 0;
        p.forceTarget = null;
        raiseWanted(1);
        state.stats.brokeIn++;
        enterRoom(door);
      }
    }

    function inRect(x, z, r) { return x > r.x0 && x < r.x1 && z > r.z0 && z < r.z1; }

    // Which room, if any, the player is standing in. Derived from position, so
    // the flag and the world can never drift apart.
    function roomAt(x, z) {
      for (var key in city.rooms) {
        if (inRect(x, z, city.rooms[key].bounds)) return key;
      }
      return false;
    }

    // Stepping onto the mat by the door puts you back on the street.
    function updateExitMat() {
      var p = state.player;
      if (!p.indoors) return;
      var zone = city.rooms[p.indoors].exitZone;
      if (inRect(p.x, p.z, zone)) leaveRoom();
    }

    // Doors open as you walk into them, the way shop doors do. You still have
    // to be heading for the door rather than wandering past it.
    function updateAutoDoors(dt, input) {
      var p = state.player;
      if (p.driving || p.soaked || state.store.open) return;
      // Any movement counts, not just walking straight forward: people sidle up
      // to doors. Still nothing while you are part way through a robbery.
      var moving = input.forward || input.back || input.left || input.right;
      if (!moving || p.robTarget) return;
      p.doorCooldown = Math.max(0, (p.doorCooldown || 0) - dt);
      if (p.doorCooldown > 0) return;

      var pos = playerPos();
      var door = nearestDoor();
      if (door.d > C.AUTO_DOOR_RANGE) return;

      if (door.kind === 'out') {
        if (headingFor(pos, city.rooms[p.indoors].exitAt)) leaveRoom();
        return;
      }
      if (!door.at || !headingFor(pos, door.at)) return;
      enterRoom(door.at);
    }

    // True when the player is walking roughly towards a point.
    function headingFor(pos, at) {
      var p = state.player;
      var dx = at.x - pos.x, dz = at.z - pos.z;
      var len = Math.hypot(dx, dz) || 1;
      var dot = (dx / len) * forwardX(p.yaw) + (dz / len) * forwardZ(p.yaw);
      return Math.acos(clamp(dot, -1, 1)) < C.AUTO_DOOR_FACING;
    }

    function updateRobbery(dt, input) {
      var p = state.player;
      if (!p.robTarget) return;
      var pos = playerPos();
      var l = p.robTarget;

      if (!input.interact || dist(pos.x, pos.z, l.x, l.z) > C.ROB_RANGE || p.soaked) {
        p.robbing = 0;
        p.robTarget = null;
        return;
      }

      p.robbing += dt * (p.perks.quick ? 2 : 1);
      if (p.robbing >= C.ROB_TIME) {
        p.money += l.cash;
        l.cool = C.ROB_COOLDOWN;
        p.robbing = 0;
        p.robTarget = null;
        state.stats.robbed++;
        awardXp(l.kind === 'safe' ? 120 : l.kind === 'register' ? 55 : 30, 'robbery');
        raiseWanted(l.kind === 'safe' ? 4 : l.kind === 'vault' ? 3 : l.kind === 'register' ? 2 : 1);
        say('+$' + l.cash + ' from the ' + labelFor(l.kind), 2.6);
      }
    }

    function labelFor(kind) {
      if (kind === 'atm') return 'cash machine';
      if (kind === 'register') return 'till';
      if (kind === 'safe') return 'bank safe';
      return 'bank vault';
    }

    // --- main step --------------------------------------------------------------

    function update(dt, input) {
      input = input || {};
      if (dt > 0.1) dt = 0.1;
      state.t += dt;
      state.timeOfDay = (state.timeOfDay + dt / C.DAY_LENGTH) % 1;
      var p = state.player;

      if (p.soaked) {
        p.soakTimer -= dt;
        if (p.soakTimer <= 0) {
          p.soaked = false;
          p.health = p.maxHealth;
          p.driving = false;
          p.car = null;
          p.x = spawnX; p.z = spawnZ;
          state.wanted = 0;
          state.cops.length = 0;
          state.darts.length = 0;
          say('you dried off. your money is safe.', 3);
        }
      } else {
        if (!state.store.open) {
          if (p.driving && p.car) driveCar(dt, input); else moveOnFoot(dt, input);
          updateRobbery(dt, input);
          updateBreakIn(dt, input);
          updateAutoDoors(dt, input);
          updateExitMat();
          updateGroundPickups();
          // Position decides where you are, not a flag someone forgot to clear.
          p.indoors = roomAt(p.x, p.z);
        }
      }

      if (p.fireCooldown > 0) p.fireCooldown -= dt;
      if (input.fire) {
        if (currentWeapon()) tryShoot(); else tryMelee();
      }

      updateTraffic(dt);
      updatePolice(dt);
      updateCivilians(dt);
      updateDarts(dt);

      // Health comes back on its own once nobody has hit you for a while.
      if (!p.soaked && state.t - p.hurtAt > C.REGEN_DELAY && p.health < p.maxHealth) {
        p.health = Math.min(p.maxHealth, p.health + C.REGEN_RATE * dt);
      }

      for (var i = 0; i < city.loot.length; i++) {
        if (city.loot[i].cool > 0) city.loot[i].cool -= dt;
      }
      for (var e = state.events.length - 1; e >= 0; e--) {
        state.events[e].life -= dt;
        if (state.events[e].life <= 0) state.events.splice(e, 1);
      }

      return state;
    }

    function look(dx, dy) {
      var p = state.player;
      p.yaw -= dx;
      p.pitch = clamp(p.pitch - dy, -1.35, 1.35);
    }

    return {
      C: C,
      state: state,
      update: update,
      look: look,
      interact: interact,
      shoot: tryShoot,
      blocked: blocked,
      onRoad: onRoad,
      nearestLoot: nearestLoot,
      nearestCar: nearestCar,
      nearestGun: nearestGun,
      melee: tryMelee,
      dropWeapon: dropWeapon,
      nearestStore: nearestStore,
      nearestDoor: nearestDoor,
      currentWeapon: currentWeapon,
      giveWeapon: giveWeapon,
      switchWeapon: switchWeapon,
      selectSlot: selectSlot,
      useMedkit: useMedkit,
      buy: buy,
      weapons: WEAPONS,
      perks: PERKS,
      inventory: inventory,
      nearestChest: nearestChest,
      enterRoom: enterRoom,
      leaveRoom: leaveRoom,
      openChest: openChest,
      awardXp: awardXp,
      playerPos: playerPos,
      spawnCop: spawnCop,
      spawnCivilian: spawnCivilian,
      hurtCivilian: hurtCivilian,
      raiseWanted: raiseWanted,
      hurtPlayer: hurtPlayer,
      hurtCop: hurtCop,
    };
  }

  return { createGame: createGame, C: C, mulberry32: mulberry32 };
});
