// GTA Fun — the simulation. Pure numbers: no Three.js, no DOM, no canvas.
// Everything the game *is* lives here; rendering only reads this state.
// That split is what lets the whole game be playtested headlessly in Node.
(function (root, factory) {
  var api = factory();
  if (typeof module === 'object' && module.exports) module.exports = api;
  else root.SIM = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  'use strict';

  // Native sizes of the Kenney models, generated by tools/build-models.js.
  // The sim needs them so collision boxes match what you actually see.
  var META = (typeof module === 'object' && module.exports)
    ? require('./model-meta.js')
    : (typeof globalThis !== 'undefined' ? globalThis.MODEL_META : null);

  var BUILDING_MODELS = ['building-a', 'building-c', 'building-e', 'building-h',
    'building-k', 'building-n', 'tower-a', 'tower-c'];
  var CAR_MODELS = ['car-sedan', 'car-taxi', 'car-van', 'car-suv', 'car-sports'];

  // Uniform scale that makes a model's footprint fill a lot of the given size.
  function fitScale(name, target) {
    var m = META && META[name];
    if (!m) return { scale: 1, w: target, d: target, h: target };
    var scale = target / Math.max(m.w, m.d);
    return { scale: scale, w: m.w * scale, d: m.d * scale, h: m.h * scale };
  }

  var C = {
    BLOCKS: 6,
    BLOCK: 60,
    ROAD: 18,
    WALK: 6.2,
    SPRINT: 9.4,
    PLAYER_R: 0.6,
    EYE: 1.7,

    CAR_MAX: 30,
    CAR_ACCEL: 16,
    CAR_BRAKE: 26,
    CAR_DRAG: 0.7,
    CAR_TURN: 1.7,
    CAR_R: 1.7,

    MAX_HEALTH: 100,
    REGEN_DELAY: 6,
    REGEN_RATE: 5,

    COP_HEALTH: 100,
    COP_SPEED: 4.6,
    COP_RANGE: 22,
    COP_STANDOFF: 9,
    // Tuned down hard after a playtest: at 7 damage every 1.35s, three officers
    // took a standing player from 100 to 23 in ten seconds. These are children.
    COP_FIRE_DELAY: 2.0,
    COP_DART_SPEED: 34,
    COP_DART_DAMAGE: 4,
    // Half a second of grace after each hit, so a crowd of officers cannot
    // stack their volleys and melt you before you can react.
    HIT_GRACE: 0.5,

    DART_SPEED: 55,
    DART_DAMAGE: 14,
    DART_LIFE: 2.2,
    FIRE_DELAY: 0.22,
    MAG: 40,

    MAX_WANTED: 5,
    WANTED_DECAY: 28,
    ROB_TIME: 2.6,
    ROB_RANGE: 3.4,
    ROB_COOLDOWN: 45,
    ENTER_RANGE: 4.0,
    PICKUP_RANGE: 2.2,

    MAX_COPS: 10,
    MAX_POLICE_CARS: 4,
  };

  C.WORLD = C.BLOCKS * C.BLOCK;
  C.HALF_ROAD = C.ROAD / 2;

  function mulberry32(a) {
    return function () {
      a |= 0; a = (a + 0x6D2B79F5) | 0;
      var t = Math.imul(a ^ (a >>> 15), 1 | a);
      t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
      return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    };
  }

  function clamp(v, lo, hi) { return v < lo ? lo : v > hi ? hi : v; }
  function dist2(ax, az, bx, bz) { var dx = ax - bx, dz = az - bz; return dx * dx + dz * dz; }
  function dist(ax, az, bx, bz) { return Math.sqrt(dist2(ax, az, bx, bz)); }

  // Yaw 0 looks down -Z, matching the renderer's camera.
  function forwardX(yaw) { return -Math.sin(yaw); }
  function forwardZ(yaw) { return -Math.cos(yaw); }

  // --- city -----------------------------------------------------------------

  function buildCity(rnd) {
    var boxes = [];          // solid AABBs: buildings and the town wall
    var buildings = [];      // placed Kenney models, with the scale to draw them at
    var loot = [];
    var guns = [];
    var props = [];          // pure decoration: lamps, trees, bins
    var blockInfo = [];

    var inner = C.BLOCK - C.ROAD;                 // 42 metres of buildable lot

    function place(name, cx, cz, target, rot) {
      var fit = fitScale(name, target);
      var w = (rot % 2) ? fit.d : fit.w;
      var d = (rot % 2) ? fit.w : fit.d;
      buildings.push({
        model: name, x: cx, z: cz, rot: rot * Math.PI / 2,
        scale: fit.scale, w: w, d: d, h: fit.h
      });
      boxes.push({ x0: cx - w / 2, z0: cz - d / 2, x1: cx + w / 2, z1: cz + d / 2 });
      return { w: w, d: d, h: fit.h };
    }

    for (var j = 0; j < C.BLOCKS; j++) {
      for (var i = 0; i < C.BLOCKS; i++) {
        var x0 = i * C.BLOCK + C.HALF_ROAD;
        var z0 = j * C.BLOCK + C.HALF_ROAD;
        var cx = x0 + inner / 2, cz = z0 + inner / 2;
        var isBank = (i === 2 && j === 3) || (i === 4 && j === 1);
        blockInfo.push({ i: i, j: j, x0: x0, z0: z0, w: inner, bank: isBank });

        if (isBank) {
          var bank = place('bank', cx, cz, inner - 8, 0);
          // The vault door sits on the street-facing wall, where you can reach it.
          loot.push({
            kind: 'vault', cash: 2500, cool: 0,
            x: cx, z: cz + bank.d / 2 + 1.6, facing: 0
          });
          props.push({ model: 'tree', x: cx - bank.w / 2 - 4, z: cz + bank.d / 2 + 2, rot: 0, size: 6 });
          props.push({ model: 'tree', x: cx + bank.w / 2 + 4, z: cz + bank.d / 2 + 2, rot: 0, size: 6 });
          continue;
        }

        // One big building, or four smaller ones with alleys between them.
        if (rnd() < 0.4) {
          place(BUILDING_MODELS[Math.floor(rnd() * BUILDING_MODELS.length)],
            cx, cz, inner - 6, Math.floor(rnd() * 4));
        } else {
          var cell = inner / 2;
          for (var lj = 0; lj < 2; lj++) {
            for (var li = 0; li < 2; li++) {
              if (rnd() < 0.15) {
                // An empty lot: park it out rather than leaving a hole.
                props.push({
                  model: 'tree', rot: 0, size: 5 + rnd() * 3,
                  x: x0 + li * cell + cell / 2, z: z0 + lj * cell + cell / 2
                });
                continue;
              }
              place(BUILDING_MODELS[Math.floor(rnd() * BUILDING_MODELS.length)],
                x0 + li * cell + cell / 2, z0 + lj * cell + cell / 2,
                cell - 4, Math.floor(rnd() * 4));
            }
          }
        }

        // A cash machine against the pavement, always facing a road.
        var side = Math.floor(rnd() * 4);
        var atm = { kind: 'atm', cash: 260, cool: 0 };
        if (side === 0) { atm.x = cx; atm.z = z0 - 1.4; atm.facing = Math.PI; }
        else if (side === 1) { atm.x = cx; atm.z = z0 + inner + 1.4; atm.facing = 0; }
        else if (side === 2) { atm.x = x0 - 1.4; atm.z = cz; atm.facing = Math.PI / 2; }
        else { atm.x = x0 + inner + 1.4; atm.z = cz; atm.facing = -Math.PI / 2; }
        loot.push(atm);

        // Every third block gets a market till on the opposite pavement.
        if ((i + j) % 3 === 0) {
          var s2 = (side + 2) % 4;
          var reg = { kind: 'register', cash: 480, cool: 0 };
          if (s2 === 0) { reg.x = cx + 7; reg.z = z0 - 1.6; reg.facing = Math.PI; }
          else if (s2 === 1) { reg.x = cx - 7; reg.z = z0 + inner + 1.6; reg.facing = 0; }
          else if (s2 === 2) { reg.x = x0 - 1.6; reg.z = cz + 7; reg.facing = Math.PI / 2; }
          else { reg.x = x0 + inner + 1.6; reg.z = cz - 7; reg.facing = -Math.PI / 2; }
          loot.push(reg);
        }

        if (rnd() < 0.4) guns.push({ x: cx + (rnd() - 0.5) * 10, z: z0 - 3, taken: false });
        if (rnd() < 0.5) {
          props.push({
            model: 'dumpster', rot: rnd() * 6.28, size: 2.2,
            x: x0 + 2 + rnd() * (inner - 4), z: z0 + inner + 2.5
          });
        }
      }
    }

    // Street lighting on every corner, and lamps down the long roads.
    for (var gj = 0; gj <= C.BLOCKS; gj++) {
      for (var gi = 0; gi <= C.BLOCKS; gi++) {
        var ix = gi * C.BLOCK, iz = gj * C.BLOCK;
        props.push({ model: 'traffic-light', x: ix - C.HALF_ROAD - 1.2, z: iz - C.HALF_ROAD - 1.2, rot: 0, size: 5 });
        if (gi < C.BLOCKS) props.push({ model: 'streetlight', x: ix + C.BLOCK / 2, z: iz - C.HALF_ROAD - 1, rot: 0, size: 6 });
        if (gj < C.BLOCKS) props.push({ model: 'streetlight', x: ix - C.HALF_ROAD - 1, z: iz + C.BLOCK / 2, rot: Math.PI / 2, size: 6 });
      }
    }

    // A wall around town so nobody drives off the edge of it.
    var lo = -C.HALF_ROAD - 4, hi = C.WORLD - C.HALF_ROAD + 4;
    boxes.push({ x0: lo - 6, z0: lo - 6, x1: lo, z1: hi + 6 });
    boxes.push({ x0: hi, z0: lo - 6, x1: hi + 6, z1: hi + 6 });
    boxes.push({ x0: lo - 6, z0: lo - 6, x1: hi + 6, z1: lo });
    boxes.push({ x0: lo - 6, z0: hi, x1: hi + 6, z1: hi + 6 });

    return {
      boxes: boxes, buildings: buildings, loot: loot,
      guns: guns, props: props, blocks: blockInfo
    };
  }

  // Roads run along every multiple of BLOCK, in both directions.
  function onRoad(x, z) {
    return nearLine(x) || nearLine(z);
  }
  function nearLine(v) {
    var k = Math.round(v / C.BLOCK);
    if (k < 0 || k > C.BLOCKS) return false;
    return Math.abs(v - k * C.BLOCK) <= C.HALF_ROAD;
  }

  function createGame(options) {
    options = options || {};
    var rnd = mulberry32(options.seed == null ? 20260823 : options.seed);
    var city = buildCity(rnd);

    var grid = {};
    var CELL = C.BLOCK;
    for (var b = 0; b < city.boxes.length; b++) {
      var box = city.boxes[b];
      for (var gz = Math.floor(box.z0 / CELL); gz <= Math.floor(box.z1 / CELL); gz++) {
        for (var gx = Math.floor(box.x0 / CELL); gx <= Math.floor(box.x1 / CELL); gx++) {
          var k = gx + ':' + gz;
          (grid[k] || (grid[k] = [])).push(b);
        }
      }
    }

    function blocked(x, z, r) {
      for (var gz = Math.floor((z - r) / CELL); gz <= Math.floor((z + r) / CELL); gz++) {
        for (var gx = Math.floor((x - r) / CELL); gx <= Math.floor((x + r) / CELL); gx++) {
          var list = grid[gx + ':' + gz];
          if (!list) continue;
          for (var i = 0; i < list.length; i++) {
            var s = city.boxes[list[i]];
            if (x + r > s.x0 && x - r < s.x1 && z + r > s.z0 && z - r < s.z1) return true;
          }
        }
      }
      return false;
    }

    var spawnX = C.BLOCK * 3;
    var spawnZ = C.BLOCK * 3;

    var state = {
      t: 0,
      seed: options.seed == null ? 20260823 : options.seed,
      city: city,
      player: {
        x: spawnX, z: spawnZ, yaw: 0, pitch: 0,
        health: C.MAX_HEALTH, money: 0,
        driving: false, car: null,
        hasGun: false, ammo: 0,
        fireCooldown: 0, hurtAt: -99, robbing: 0, robTarget: null,
        soaked: false, soakTimer: 0, bob: 0
      },
      cars: [],
      cops: [],
      darts: [],
      wanted: 0,
      wantedDecay: 0,
      events: [],
      stats: { robbed: 0, copsDropped: 0, carsStolen: 0, timesSoaked: 0 },
    };

    // --- traffic and parked cars ---------------------------------------------

    function laneSpot(axis, line, along, dir) {
      // Right-hand traffic: offset half a lane from the centre line.
      var off = 4.4 * dir;
      return axis === 'x'
        ? { x: along, z: line + off }
        : { x: line - off, z: along };
    }

    function spawnTraffic(n) {
      for (var i = 0; i < n; i++) {
        var axis = rnd() < 0.5 ? 'x' : 'z';
        var line = (1 + Math.floor(rnd() * (C.BLOCKS - 1))) * C.BLOCK;
        var dir = rnd() < 0.5 ? 1 : -1;
        var along = 20 + rnd() * (C.WORLD - 40);
        var p = laneSpot(axis, line, along, dir);
        state.cars.push({
          x: p.x, z: p.z, angle: headingFor(axis, dir), speed: 8 + rnd() * 8,
          axis: axis, line: line, dir: dir, cruise: 9 + rnd() * 8,
          kind: 'civilian', ai: true, parked: false,
          model: CAR_MODELS[Math.floor(rnd() * CAR_MODELS.length)],
          health: 100, siren: 0
        });
      }
    }

    function spawnParked(n) {
      for (var i = 0; i < n; i++) {
        var axis = rnd() < 0.5 ? 'x' : 'z';
        var line = Math.floor(rnd() * (C.BLOCKS + 1)) * C.BLOCK;
        var dir = rnd() < 0.5 ? 1 : -1;
        var along = 15 + rnd() * (C.WORLD - 30);
        var p = laneSpot(axis, line, along, dir);
        if (blocked(p.x, p.z, C.CAR_R)) continue;
        state.cars.push({
          x: p.x, z: p.z, angle: headingFor(axis, dir), speed: 0,
          axis: axis, line: line, dir: dir, cruise: 0,
          kind: 'civilian', ai: false, parked: true,
          model: CAR_MODELS[Math.floor(rnd() * CAR_MODELS.length)],
          health: 100, siren: 0
        });
      }
      // Always one on the kerb where you start, so the game opens with a car.
      state.cars.push({
        x: spawnX + 6, z: spawnZ + 4.4, angle: headingFor('x', 1), speed: 0,
        axis: 'x', line: spawnZ, dir: 1, cruise: 0,
        kind: 'civilian', ai: false, parked: true,
        model: CAR_MODELS[0], health: 100, siren: 0
      });
    }

    function headingFor(axis, dir) {
      if (axis === 'x') return dir > 0 ? -Math.PI / 2 : Math.PI / 2;
      return dir > 0 ? Math.PI : 0;
    }

    spawnTraffic(14);
    spawnParked(12);

    // --- helpers --------------------------------------------------------------

    function say(text, seconds) {
      state.events.push({ text: text, life: seconds || 2.4 });
      if (state.events.length > 6) state.events.shift();
    }

    function raiseWanted(n) {
      state.wanted = Math.min(C.MAX_WANTED, state.wanted + n);
      state.wantedDecay = C.WANTED_DECAY;
    }

    function playerPos() {
      var p = state.player;
      if (p.driving && p.car) return { x: p.car.x, z: p.car.z };
      return { x: p.x, z: p.z };
    }

    function nearestLoot() {
      var pos = playerPos(), best = null, bestD = Infinity;
      for (var i = 0; i < city.loot.length; i++) {
        var l = city.loot[i];
        var d = dist(pos.x, pos.z, l.x, l.z);
        if (d < bestD) { bestD = d; best = l; }
      }
      return { loot: best, d: bestD };
    }

    function nearestCar() {
      var pos = playerPos(), best = null, bestD = Infinity;
      for (var i = 0; i < state.cars.length; i++) {
        var c = state.cars[i];
        if (c === state.player.car) continue;
        var d = dist(pos.x, pos.z, c.x, c.z);
        if (d < bestD) { bestD = d; best = c; }
      }
      return { car: best, d: bestD };
    }

    // --- movement -------------------------------------------------------------

    function moveOnFoot(dt, input) {
      var p = state.player;
      var fx = forwardX(p.yaw), fz = forwardZ(p.yaw);
      var rx = -fz, rz = fx;                       // right-hand vector
      var mx = 0, mz = 0;
      if (input.forward) { mx += fx; mz += fz; }
      if (input.back) { mx -= fx; mz -= fz; }
      if (input.right) { mx += rx; mz += rz; }
      if (input.left) { mx -= rx; mz -= rz; }

      var len = Math.hypot(mx, mz);
      if (len > 0) {
        mx /= len; mz /= len;
        var speed = input.sprint ? C.SPRINT : C.WALK;
        p.bob += dt * speed;
        var nx = p.x + mx * speed * dt;
        if (!blocked(nx, p.z, C.PLAYER_R)) p.x = nx;
        var nz = p.z + mz * speed * dt;
        if (!blocked(p.x, nz, C.PLAYER_R)) p.z = nz;
      }
    }

    function driveCar(dt, input) {
      var p = state.player, car = p.car;
      if (input.forward) car.speed += C.CAR_ACCEL * dt;
      else if (input.back) car.speed -= C.CAR_BRAKE * dt;
      car.speed -= car.speed * C.CAR_DRAG * dt;
      car.speed = clamp(car.speed, -10, C.CAR_MAX);

      var steer = (input.left ? 1 : 0) - (input.right ? 1 : 0);
      car.angle += steer * C.CAR_TURN * (car.speed / C.CAR_MAX) * dt * 2.2;

      var nx = car.x + forwardX(car.angle) * car.speed * dt;
      var nz = car.z + forwardZ(car.angle) * car.speed * dt;
      if (!blocked(nx, nz, C.CAR_R)) { car.x = nx; car.z = nz; }
      else { car.speed *= -0.28; }

      p.x = car.x; p.z = car.z;
    }

    function updateTraffic(dt) {
      for (var i = 0; i < state.cars.length; i++) {
        var car = state.cars[i];
        if (!car.ai || car === state.player.car) continue;

        if (car.kind === 'police') { chaseWithCar(car, dt); continue; }

        car.speed += (car.cruise - car.speed) * Math.min(1, dt * 1.5);
        var along = car.axis === 'x' ? car.x : car.z;
        var next = along + car.dir * car.speed * dt;
        var k = car.dir > 0 ? Math.ceil(along / C.BLOCK) : Math.floor(along / C.BLOCK);
        var cross = k * C.BLOCK;
        var passing = car.dir > 0 ? next >= cross : next <= cross;

        if (passing && cross >= 0 && cross <= C.WORLD) {
          var forced = cross <= 0 || cross >= C.WORLD;
          if (forced || rnd() < 0.35) {
            var oldLine = car.line;
            car.axis = car.axis === 'x' ? 'z' : 'x';
            car.line = cross;
            car.dir = rnd() < 0.5 ? 1 : -1;
            var spot = laneSpot(car.axis, car.line, oldLine, car.dir);
            car.x = spot.x; car.z = spot.z;
            car.angle = headingFor(car.axis, car.dir);
            car.speed *= 0.6;
            continue;
          }
        }
        if (next < -C.HALF_ROAD || next > C.WORLD + C.HALF_ROAD) { car.dir *= -1; continue; }

        var lane = laneSpot(car.axis, car.line, next, car.dir);
        car.x += (lane.x - car.x) * Math.min(1, dt * 5);
        car.z += (lane.z - car.z) * Math.min(1, dt * 5);
        if (car.axis === 'x') car.x = next; else car.z = next;
        car.angle = headingFor(car.axis, car.dir);
      }
    }

    // Police cars drive straight at you and give up gracefully on walls.
    function chaseWithCar(car, dt) {
      var pos = playerPos();
      var want = Math.atan2(-(pos.x - car.x), -(pos.z - car.z));
      var diff = ((want - car.angle + Math.PI * 3) % (Math.PI * 2)) - Math.PI;
      car.angle += clamp(diff, -C.CAR_TURN * dt * 2, C.CAR_TURN * dt * 2);

      var gap = dist(pos.x, pos.z, car.x, car.z);
      var target = gap > 16 ? 22 : 8;
      car.speed += (target - car.speed) * Math.min(1, dt * 1.2);
      car.siren += dt;

      var nx = car.x + forwardX(car.angle) * car.speed * dt;
      var nz = car.z + forwardZ(car.angle) * car.speed * dt;
      if (!blocked(nx, nz, C.CAR_R)) { car.x = nx; car.z = nz; }
      else { car.speed *= -0.2; car.angle += 0.6 * dt * 4; }

      // Close enough: the officers get out and continue on foot.
      if (gap < 18 && !car.emptied) {
        car.emptied = true;
        spawnCop(car.x + 2.2, car.z + 2.2);
        if (state.wanted >= 3) spawnCop(car.x - 2.2, car.z - 2.2);
      }
    }

    // --- police ----------------------------------------------------------------

    function spawnCop(x, z) {
      if (state.cops.length >= C.MAX_COPS) return null;
      var cop = {
        x: x, z: z, health: C.COP_HEALTH, cooldown: 0.8 + rnd() * 0.8,
        state: 'chase', sat: 0, bob: rnd() * 6
      };
      state.cops.push(cop);
      return cop;
    }

    function spawnPoliceCar() {
      var count = 0;
      for (var i = 0; i < state.cars.length; i++) if (state.cars[i].kind === 'police') count++;
      if (count >= C.MAX_POLICE_CARS) return;

      var pos = playerPos();
      // Arrive along a road, from off in the distance.
      var axis = rnd() < 0.5 ? 'x' : 'z';
      var line = Math.round((axis === 'x' ? pos.z : pos.x) / C.BLOCK) * C.BLOCK;
      line = clamp(line, 0, C.WORLD);
      var dir = rnd() < 0.5 ? 1 : -1;
      var along = clamp((axis === 'x' ? pos.x : pos.z) - dir * 60, 5, C.WORLD - 5);
      var spot = laneSpot(axis, line, along, dir);
      state.cars.push({
        x: spot.x, z: spot.z, angle: headingFor(axis, dir), speed: 14,
        axis: axis, line: line, dir: dir, cruise: 20,
        kind: 'police', ai: true, parked: false, model: 'car-police',
        health: 100, siren: 0, emptied: false
      });
    }

    var copSpawnTimer = 0;
    var carSpawnTimer = 0;

    function updatePolice(dt) {
      var pos = playerPos();
      var p = state.player;

      if (state.wanted > 0) {
        state.wantedDecay -= dt;
        if (state.wantedDecay <= 0) {
          state.wanted--;
          state.wantedDecay = C.WANTED_DECAY;
          if (state.wanted === 0) say('the police have lost interest', 3);
        }

        copSpawnTimer -= dt;
        if (copSpawnTimer <= 0 && state.cops.length < state.wanted + 1) {
          var ang = rnd() * Math.PI * 2;
          var d = 34 + rnd() * 18;
          var cx = clamp(pos.x + Math.cos(ang) * d, 4, C.WORLD - 4);
          var cz = clamp(pos.z + Math.sin(ang) * d, 4, C.WORLD - 4);
          if (!blocked(cx, cz, 0.8)) spawnCop(cx, cz);
          copSpawnTimer = 2.2;
        }

        carSpawnTimer -= dt;
        if (state.wanted >= 2 && carSpawnTimer <= 0) {
          spawnPoliceCar();
          carSpawnTimer = 9;
        }
      } else {
        // Everyone goes home when the heat is off.
        for (var q = state.cops.length - 1; q >= 0; q--) {
          if (dist(pos.x, pos.z, state.cops[q].x, state.cops[q].z) > 45) state.cops.splice(q, 1);
        }
        for (var r = state.cars.length - 1; r >= 0; r--) {
          if (state.cars[r].kind === 'police' &&
              dist(pos.x, pos.z, state.cars[r].x, state.cars[r].z) > 55) state.cars.splice(r, 1);
        }
      }

      for (var i = state.cops.length - 1; i >= 0; i--) {
        var cop = state.cops[i];

        if (cop.state === 'sat') {
          cop.sat -= dt;
          if (cop.sat <= 0) state.cops.splice(i, 1);
          continue;
        }

        var gap = dist(pos.x, pos.z, cop.x, cop.z);
        cop.bob += dt * 6;

        if (gap > C.COP_STANDOFF) {
          var dx = (pos.x - cop.x) / (gap || 1), dz = (pos.z - cop.z) / (gap || 1);
          var nx = cop.x + dx * C.COP_SPEED * dt;
          if (!blocked(nx, cop.z, 0.6)) cop.x = nx;
          var nz = cop.z + dz * C.COP_SPEED * dt;
          if (!blocked(cop.x, nz, 0.6)) cop.z = nz;
        }

        cop.cooldown -= dt;
        if (gap < C.COP_RANGE && cop.cooldown <= 0 && !p.soaked) {
          cop.cooldown = C.COP_FIRE_DELAY;
          fireDart(cop.x, 1.4, cop.z, pos.x, p.driving ? 1.0 : 1.3, pos.z,
            C.COP_DART_SPEED, 'police', C.COP_DART_DAMAGE, 0.16);
        }
      }
    }

    // --- darts -----------------------------------------------------------------

    function fireDart(x, y, z, tx, ty, tz, speed, owner, damage, spread) {
      var dx = tx - x, dy = ty - y, dz = tz - z;
      var len = Math.hypot(dx, dy, dz) || 1;
      dx /= len; dy /= len; dz /= len;
      if (spread) {
        dx += (rnd() - 0.5) * spread;
        dy += (rnd() - 0.5) * spread * 0.5;
        dz += (rnd() - 0.5) * spread;
      }
      state.darts.push({
        x: x, y: y, z: z,
        vx: dx * speed, vy: dy * speed, vz: dz * speed,
        life: C.DART_LIFE, owner: owner, damage: damage
      });
    }

    function updateDarts(dt) {
      var p = state.player;
      var pos = playerPos();
      for (var i = state.darts.length - 1; i >= 0; i--) {
        var d = state.darts[i];
        d.life -= dt;
        d.vy -= 7 * dt;                                  // foam darts droop
        d.x += d.vx * dt; d.y += d.vy * dt; d.z += d.vz * dt;

        var gone = d.life <= 0 || d.y < 0.05 || blocked(d.x, d.z, 0.12);

        if (!gone && d.owner === 'police' && !p.soaked) {
          var hitR = p.driving ? 2.0 : 0.85;
          if (dist(d.x, d.z, pos.x, pos.z) < hitR && d.y < (p.driving ? 2.2 : 2.0)) {
            hurtPlayer(d.damage);
            gone = true;
          }
        }
        if (!gone && d.owner === 'player') {
          for (var c = 0; c < state.cops.length; c++) {
            var cop = state.cops[c];
            if (cop.state === 'sat') continue;
            if (dist(d.x, d.z, cop.x, cop.z) < 0.95 && d.y > 0.2 && d.y < 2.3) {
              hurtCop(cop, d.damage);
              gone = true;
              break;
            }
          }
        }
        if (gone) state.darts.splice(i, 1);
      }
    }

    function hurtPlayer(amount, graceless) {
      var p = state.player;
      if (!graceless && state.t - p.hurtAt < C.HIT_GRACE) return;
      p.health = Math.max(0, p.health - amount);
      p.hurtAt = state.t;
      if (p.health <= 0 && !p.soaked) {
        p.soaked = true;
        p.soakTimer = 2.6;
        state.stats.timesSoaked++;
        say('SOAKED — you sit this one out for a moment', 3);
      }
    }

    function hurtCop(cop, amount) {
      cop.health -= amount;
      if (cop.health <= 0 && cop.state !== 'sat') {
        cop.state = 'sat';
        cop.sat = 9;
        state.stats.copsDropped++;
        say('officer sits down for a bit', 2);
        // A dropped officer leaves their nerf gun behind.
        city.guns.push({ x: cop.x, z: cop.z, taken: false });
      }
    }

    // --- actions ---------------------------------------------------------------

    function tryShoot() {
      var p = state.player;
      if (p.soaked || !p.hasGun || p.ammo <= 0 || p.fireCooldown > 0) return false;
      p.fireCooldown = C.FIRE_DELAY;
      p.ammo--;

      var fx = forwardX(p.yaw) * Math.cos(p.pitch);
      var fz = forwardZ(p.yaw) * Math.cos(p.pitch);
      var fy = Math.sin(p.pitch);
      var pos = playerPos();
      var eye = p.driving ? 1.2 : C.EYE;
      state.darts.push({
        x: pos.x + fx * 0.7, y: eye + fy * 0.7, z: pos.z + fz * 0.7,
        vx: fx * C.DART_SPEED, vy: fy * C.DART_SPEED, vz: fz * C.DART_SPEED,
        life: C.DART_LIFE, owner: 'player', damage: C.DART_DAMAGE
      });
      // Shooting at the police is, understandably, a crime.
      if (state.wanted < 1) raiseWanted(1);
      return true;
    }

    // E is the only interaction key: it does whatever you are standing next to.
    function interact() {
      var p = state.player;
      if (p.soaked) return 'none';

      if (p.driving) {
        var car = p.car;
        car.speed = 0;
        if (car.kind === 'civilian') { car.ai = true; car.parked = true; }
        p.driving = false;
        p.car = null;
        p.x = car.x + 2.6;
        p.z = car.z + 2.6;
        say('out of the car', 1.4);
        return 'exit';
      }

      var gun = nearestGun();
      if (gun.gun && gun.d < C.PICKUP_RANGE) {
        gun.gun.taken = true;
        p.hasGun = true;
        p.ammo = C.MAG;
        say('picked up a nerf blaster — click to fire', 2.6);
        return 'gun';
      }

      var near = nearestLoot();
      if (near.loot && near.d < C.ROB_RANGE) {
        if (near.loot.cool > 0) { say('this one is empty for now', 1.6); return 'empty'; }
        p.robTarget = near.loot;
        p.robbing = 0.0001;                         // held-E progress starts
        return 'rob';
      }

      var found = nearestCar();
      if (found.car && found.d < C.ENTER_RANGE) {
        p.driving = true;
        p.car = found.car;
        found.car.ai = false;
        found.car.parked = false;
        found.car.emptied = true;
        if (found.car.kind === 'police') say('you are now driving: A POLICE CAR', 2.6);
        else say('you are now driving: A CAR', 2.2);
        state.stats.carsStolen++;
        // Taking someone's car in front of them is noticed.
        raiseWanted(1);
        return 'enter';
      }
      return 'none';
    }

    function nearestGun() {
      var pos = playerPos(), best = null, bestD = Infinity;
      for (var i = 0; i < city.guns.length; i++) {
        var g = city.guns[i];
        if (g.taken) continue;
        var d = dist(pos.x, pos.z, g.x, g.z);
        if (d < bestD) { bestD = d; best = g; }
      }
      return { gun: best, d: bestD };
    }

    function updateRobbery(dt, input) {
      var p = state.player;
      if (!p.robTarget) return;
      var pos = playerPos();
      var l = p.robTarget;

      if (!input.interact || dist(pos.x, pos.z, l.x, l.z) > C.ROB_RANGE || p.soaked) {
        p.robbing = 0;
        p.robTarget = null;
        return;
      }

      p.robbing += dt;
      if (p.robbing >= C.ROB_TIME) {
        p.money += l.cash;
        l.cool = C.ROB_COOLDOWN;
        p.robbing = 0;
        p.robTarget = null;
        state.stats.robbed++;
        raiseWanted(l.kind === 'vault' ? 3 : l.kind === 'register' ? 2 : 1);
        say('+$' + l.cash + ' from the ' + labelFor(l.kind), 2.6);
      }
    }

    function labelFor(kind) {
      return kind === 'atm' ? 'cash machine' : kind === 'register' ? 'till' : 'bank vault';
    }

    // --- main step --------------------------------------------------------------

    function update(dt, input) {
      input = input || {};
      if (dt > 0.1) dt = 0.1;
      state.t += dt;
      var p = state.player;

      if (p.soaked) {
        p.soakTimer -= dt;
        if (p.soakTimer <= 0) {
          p.soaked = false;
          p.health = C.MAX_HEALTH;
          p.driving = false;
          p.car = null;
          p.x = spawnX; p.z = spawnZ;
          state.wanted = 0;
          state.cops.length = 0;
          state.darts.length = 0;
          say('you dried off. your money is safe.', 3);
        }
      } else {
        if (p.driving && p.car) driveCar(dt, input); else moveOnFoot(dt, input);
        updateRobbery(dt, input);
      }

      if (p.fireCooldown > 0) p.fireCooldown -= dt;
      if (input.fire) tryShoot();

      updateTraffic(dt);
      updatePolice(dt);
      updateDarts(dt);

      // Health comes back on its own once nobody has hit you for a while.
      if (!p.soaked && state.t - p.hurtAt > C.REGEN_DELAY && p.health < C.MAX_HEALTH) {
        p.health = Math.min(C.MAX_HEALTH, p.health + C.REGEN_RATE * dt);
      }

      for (var i = 0; i < city.loot.length; i++) {
        if (city.loot[i].cool > 0) city.loot[i].cool -= dt;
      }
      for (var e = state.events.length - 1; e >= 0; e--) {
        state.events[e].life -= dt;
        if (state.events[e].life <= 0) state.events.splice(e, 1);
      }

      return state;
    }

    function look(dx, dy) {
      var p = state.player;
      p.yaw -= dx;
      p.pitch = clamp(p.pitch - dy, -1.35, 1.35);
    }

    return {
      C: C,
      state: state,
      update: update,
      look: look,
      interact: interact,
      shoot: tryShoot,
      blocked: blocked,
      onRoad: onRoad,
      nearestLoot: nearestLoot,
      nearestCar: nearestCar,
      nearestGun: nearestGun,
      playerPos: playerPos,
      spawnCop: spawnCop,
      raiseWanted: raiseWanted,
      hurtPlayer: hurtPlayer,
    };
  }

  return { createGame: createGame, C: C, mulberry32: mulberry32 };
});
